### ISSUE TITLE
Loader isn't unwrapping physical devices in extension functions

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1120]
The layer currently wraps physical devices in `terminator_EnumeratePhysicalDevices` and then unwraps on any function (e.g. `vkGetPhysicalDeviceFeatures` that goes from app -> layer dispatch chain with `loader_unwrap_physical_device`.

Unfortunately this only happens for functions in `trampoline.c`, so e.g. `vkDebugMarkerSetObjectNameEXT` goes straight through from the application to the first layer in the dispatch chain, but the application's physical device handle is to a loader-wrapped object, and if the layer tries to use it as its own type of object it will get garbage back.

I think this means that for proper function the loader needs to implement any extension that uses physical devices so it can unwrap them. Which then puts a burden on the loader to implement them and stay up to date, and means a new loader version is needed for layer support of any new extension. I think this would hold true even for the ICD implemented extensions without layers as there's no terminator function.

**Comment by MarkY-LunarG** [comment]
This is not a trivial change as the loader will have to implement not only a trampoline but also a terminator for each function that can access a physical device.  This is because the loader wraps the physical device in both, and we have to unwrap the terminator physical device pointer.  It's going to have to sit as a TODO for a while as I have other items to take care of.

**Comment by courtney-g** [comment]
Wouldn't we need to do this to support the PhysicalDevice queries we've been talking about?

**Comment by MarkY-LunarG** [comment]
This is different, it's a known function so should have a specific trampoline/terminator.  I think we already do this in our loader for one of the KHRSurface functions, I can't remember which off-hand.  Since these are "device" functions and not "physical device" functions, it has to be handled in this specific way.

**Comment by MarkY-LunarG** [comment]
Currently being fixed with pull-request #1147.

**Comment by MarkY-LunarG** [comment]
Fixed with commit  9510c1446e1a9891b57de0baba6cb298b2890893
