### ISSUE TITLE
Questionable performance warning for CB having pipeline with no vertex buffers attached

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1123]
Over at my Vulkan examples repository I was hinted at a performance warning for some of my examples that generate vertices inside the vertex shader, and as such have no vertex buffers bound for certain pipelines.

Take this scenario:
- Vertex input state for **Pipeline A** has 1 vertex binding and n vertex attributes 
- Vertex input state for **Pipeline B** has no vertex bindings and attributes (vertices are generated by the VS)

Both pipelines are used within the same primary command buffer:

```cpp
vkBeginCommandBuffer(cmdBuffer, ...);
vkCmdBeginRenderPass(cmdBuffer, ...);

...

// Pipeline A: Render from vertex buffer 
vkCmdBindDescriptorSets(...);
vkCmdBindPipeline(cmdBuffer, VK_PIPELINE_BIND_POINT_GRAPHICS, PipelineA);
vkCmdBindVertexBuffers(cmdBuffer, VERTEX_BUFFER_BIND_ID, 1, &vertexBuffer, offsets);
vkCmdBindIndexBuffer(...);
vkCmdDrawIndexed(...);

// Pipeline B: Generate vertices in VS (no vertex buffer required)
vkCmdBindDescriptorSets(...);
vkCmdBindPipeline(cmdBuffer, VK_PIPELINE_BIND_POINT_GRAPHICS, PipelineB);
vkCmdDraw(...);

...

vkCmdEndRenderPass(cmdBuffer);
vkEndCommandBuffer(cmdBuffer);
```

This will trigger the following warning
`Vertex buffers are bound to command buffer (0x214f377fd20) but no vertex buffers are attached to this Pipeline State Object (0x4b)`

Not 100% sure, but I couldn't find anything in the specs that would prohibit this and I don't see why this could be a potential performance problem.

Any thoughts on this?

**Comment by lentinem** [comment]
Performance warnings have really no direct relation with the spec and in fact may not be a problem at all but are additional information saying that it's possible some drivers may do more work than you might think. If you are looking for spec violations, errors are the only outputs that indicate that.

**Comment by tobine** [comment]
Hi @SaschaWillems. My thought is that it's a warning which are generally intended for people who may be newer to Vulkan to help steer them away from potentially bad behavior. Since you obviously know what you are doing you can safely disregard the warning.

I don't recall specifically, but I suspect that this particular warning was put in at the request of a user whose pipeline did not include vtx buffers when intended to and it caused debugging headaches. The warning should help such users.

I'm not sure why "perf warning" was chosen vs just "warning". Perhaps there was a thought that this case may be bypassing a HW's specialized unit for processing vertices? It seems like just warning would be more appropriate to me.
