### ISSUE TITLE
Unique objects does not prevent duplicate memory allocations

### ISSUE THREAD

**Issue by lentinem** [KhronosGroup/Vulkan-LoaderAndValidationLayers#129]
As states in #121 it looks like if you reuse a memory allocation the draw state layer cannot differentiate between the two even if unique objects is enabled. This should be fixed both from within draw state and from within unique objects.

**Comment by dustin-lunarg** [comment]
I ran into a related draw state issue on Friday when debugging a problem observed when running cube --validate and resizing the window. The resize produces the following message when destroying and recreating images:
ERROR: [DS] Code 6 : Cannot map an image with layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL. Only GENERAL or PREINITIALIZED are supported.
ERROR: [DS] Code 6 : Cannot submit cmd buffer using image with layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL when first use is VK_IMAGE_LAYOUT_PREINITIALIZED.

The problem was that tracked image memory, subresource, and layout data from a destroyed image was being used to validate a new image.  Unique objects doesn't prevent this as it destroys the unique object wrapper when the image is destroyed, allowing it to be reused.  

I have local draw state changes to clean up the image resources, but am not sure if they hit everything in the right places.  I'll create a PR for review. 

The messages observed are similar to those reported for issue [#48](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/48), which looks to be reporting the same issue as [#121](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/121).

**Comment by tobine** [comment]
Just posted #312 that has a simple solution to this problem. Please provide review feedback on that solution. I'm continuing to test it and am considering how much more sophisticated I need/want to make this code.

**Comment by tobine** [comment]
Final fix for this was pushed in #325
