### ISSUE TITLE
vkCreateRenderPass SIGSEGV

### ISSUE THREAD

**Issue by Scoopta** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1348]
Any time I call vkCreateRenderPass I get a seg fault and I'm not entirely sure why. It only happens if I have the validation layer enabled. Disabling it seems to fix my issue but that's not ideal. I ran into this issue before with vkDestroyImageView but that ended up being a stupid mistake I made so I've tried to find potential stupid mistakes but I haven't found any. As far as I can tell my code is fine. The seg fault happens here:
`[libVkLayer_core_validation.so+0x184475] core_validation::CreateRenderPass(VkDevice_T*, VkRenderPassCreateInfo const*, VkAllocationCallbacks const*, VkRenderPass_T**)+0x115`
This is the source code: [link](http://pastebin.com/vxwf8av0)
This is an API Dump: [link](http://pastebin.com/PxPjnvg4)

**Comment by mark-lunarg** [comment]
@Scoopta, were there no validation warnings or errors before the crash -- I didn't see any in the api dump...

**Comment by stroyan** [comment]
Your createRenderPass function never initializes createInfo.attachmentCount, createInfo.subpassCount, or createInfo.dependencyCount .

**Comment by Scoopta** [comment]
@mark-lunarg no it didn't. If I take off the createInfo.pDependencies(null)  the validation layer blows up with messages so it's working. Also @stroyan I can't and am not supposed to. LWJGL does a lot of the count stuff for you by looking at the amount you actually gave it. There is no way for me to set those and LWJGL should do it. If you print out createInfo.attachmentCount() it should be correct even though it was never set.

**Comment by karl-lunarg** [comment]
@Scoopta Is there any chance that you can run the demo program that is provided with the lwjgl package with layers enabled?  It would be interesting to see if a crash occurs with that program.

**Comment by Scoopta** [comment]
@karl-lunarg I just tried ClearScreenDemo and it doesn't happen. I checked their code against mine and added this to mine:
`subpass.pResolveAttachments(null);
subpass.pDepthStencilAttachment(null);
subpass.pPreserveAttachments(null);
subpass.pInputAttachments(null);`
That fixed the issue. I'm surprised the validation layer didn't say anything about that. I've been following the tutorial on vulkan-tutorial.com but it seems like there are a lot of things that you don't need to take into account when using vulkan natively. Either that or if nothing else the tutorial doesn't where as I've run into issues with it. I know with LWJGL if you don't explicitly set flags(0) the validation layer will tell you about it. Maybe it does that with C/C++ but if it does the tutorial doesn't mention it or do it. I guess the lesson is read all the members of each struct and if the tutorial ignores them or lists them as optional just explicitly define it.

**Comment by karl-lunarg** [comment]
A common pattern in C/C++ Vulkan applications is to allocate a *CreateInfo structure, fill it with zeros, and then fill in the parts that need to be different.

The validation layers do some parameter checking inside of these *CreateInfo structures, but generally cannot distinguish between uninitialized non-zero pointers/counts and properly initialized pointers/counts.  So if a bad pointer and a bad count are passed in, the layers may dereference the bad pointer and/or use an invalid count to walk the array pointed to by the pointer and then crash.  This wouldn't happen if the pointer and count are zero or are set to valid values.

I haven't completely studied all that java code, but the behavior observed here suggests that the RenderPass CreateInfo struct isn't getting cleared out by this java framework, which allows members that are not explicitly specified to remain at random values when the call is made.  I don't know if this is by design in this framework, or is simply an oversight or bug.

**Comment by stroyan** [comment]
I notice that some examples like
https://github.com/LWJGL/lwjgl3-demos/blob/master/src/org/lwjgl/demo/vulkan/TriangleDemo.java
are using calloc like "VkSubpassDescription.calloc(1)" instead of "VkSubpassDescription.malloc(1)".
That may cover up issues with members that are not explicitly initialized.
Actual explicit initialization does look like the best way to go.
