### ISSUE TITLE
spec.py no longer works with .39 spec

### ISSUE THREAD

**Issue by jfroy** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1398]
```
python spec.py -update
Using spec from online at https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html
Traceback (most recent call last):
  File "spec.py", line 461, in <module>
    spec.loadFile(use_online, spec_filename)
  File "spec.py", line 104, in loadFile
    self.tree = etree.parse(urllib2.urlopen(spec_url))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: mismatched tag: line 838, column 2

```

**Comment by tobine** [comment]
Yep, I see this as well. Looks like bad XML as it breaks down the ElementTree parser. I'm getting on a plane shortly so may not be able to isolate right now. But I can look into it more later and follow-up with @oddhack at F2F.

**Comment by oddhack** [comment]
The spec is HTML5 now. I don't see browsers complaining about it. If you can identify specifically what it's complaining about it might or might be something we have direct control over.

Starting with the next release the spec will be HTML5 generated by asciidoctor, instead of asciidoc and that might have different issues.

Generally speaking we do not support or expect the spec output to be consumed by anything except a browser. I have no idea what this particular script does, but as a general matter you should operate on vk.xml or on the asciidoc sources, which don't go through processing chains we have little control over. If this has something to do with the error code tagging, I am working on inserting that into the spec sources per an open issue on the vulkan repo, have just been sidetracked by extreme illness over the last 3+ weeks. If someone is coughing around you this winter, stay the hell away from them and hopefully avoid the Bronchitis Virus from Hell.

**Comment by oddhack** [comment]
N.b. it looks like line 838 means something in the \<head> section.

**Comment by oddhack** [comment]
Also, you might try pulling from https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html instead of /xhtml/vkspec.html . I think the redirects I currently have setup are not doing the right thing for included CSS / images / etc., which might bear on your problem.

**Comment by mark-lunarg** [comment]
@tobine, is this covered by the latest changes you've made?

**Comment by mark-lunarg** [comment]
If this issue persists, please reopen an issue against the 1.0.42/1.0.43 version of the spec.

**Comment by tobine** [comment]
I suspect that spec.py is still broken on latest spec but my current priority is getting VUs integrated into the spec at which point this issue will go away.
