### ISSUE TITLE
missing checks in VU error 01426

### ISSUE THREAD

**Issue by cdwfs** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1411]
VU error 01426 complains if VK_PRIMITIVE_TOPOLOGY_PATCH_LIST is used with pTessellationState->patchControlPoints outside the valid range. However, the check doesn't seem to be checking the primitive topology or the active shader stages; thus, the error triggers even in (e.g.) VS/PS use cases with triangle list topology. I can avoid the error by passing pTessellationState=NULL when creating the pipeline, but I had assumed that struct would be ignored if tessellation is disabled; is that not the case?

**Comment by mikes-lunarg** [comment]
This check was recently changed to more closely implement the valid usage statement from the spec which does not include any language about the primitive topology or shader stages.  The spec does state the following under VkGraphicsPipelineCreateInfo:

> pTessellationState is a pointer to an instance of the VkPipelineTessellationStateCreateInfo structure, or NULL if the pipeline does not include a tessellation control shader stage and tessellation evaluation shader stage.

but does not enforce this in the VkGraphicsPipelineCreateInfo Valid Usage section.

You are not the only one to assume that pTessellationState would be ignored and we have been discussing this internally since the change went in to see if we need more clarity from the spec.  At the very least, the error message currently emitted for VU 01426 misleading and needs to be updated.

**Comment by cdwfs** [comment]
Thanks for the clarification; I can set pTessellationState to NULL for now. I look forward to a clear answer from the spec.

**Comment by mikes-lunarg** [comment]
Spec update 1.0.47 includes new language to explicitly ignore pTessellationState when the pipeline does not include tessellation control/evaluation stages.  Validation should be updated to skip the VU 1426 check in this case.
