### ISSUE TITLE
Core Validation: ValidtateBufferBounds may reports incorrect error for compressed image formats

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1507]
Hi,

if the copy extend of one of the regions is smaller than the block size of the compressed image format, then the range check becomes invalid as `copy_extent.height - 1`
in https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/buffer_validation.cpp#L2724 underflows.

As it is a invalid copy command, it should be reported on an earlier check (ValidateImageBounds may be?)

**Comment by daveh-lunarg** [comment]
There is a valid usage check that might have caught this (not yet implemented, #1270). _Might_, because the spec language is slightly vague in that it doesn't disallow an extent of 0 for w,h - which is why this check was deferred previously.  Since Tiemo has managed to hit it, I'll avoid the underflow for now and replace it with the official valid usage once it's clarified.

**Comment by daveh-lunarg** [comment]
This issue should be resolved with PR1530.  Thanks for the report!
