### ISSUE TITLE
vkCreateSwapChainKHR() called with imageExtent which is not equal to the currentExtent.

### ISSUE THREAD

**Issue by nco2k** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1512]
i dont really understand the reason for this error. does the imageExtent really have to always match the currentExtent? if not, maybe this should be changed to a warning instead.

i am letting the user select two different resolutions. one for the windowed mode and one for the fullscreen mode. if the windowed mode is for example 1280x720 and the fullscreen mode is for example 1024x768, then i use the bigger values and create a surface of 1280x768. the reason i do this is to quickly being able to switch between the windowed and fullscreen mode, without the need to unnecessarily recreate the whole swapchain etc.

i also cant recall directx ever complaining about this, so i wonder if this is really considered an error in the vulkan api? as long as the selected extent is in the range between minImageExtent and maxImageExtent (which it is in this case) everything should be alright, right? please enlighten me if im wrong.

**Comment by ianelliottus** [comment]
What "platform" (window system) are you using? Different platforms have different valid usage rules.

**Comment by nco2k** [comment]
sorry, im using windows 7 64bit. despite that error message, everything seems to work fine so far. so i wonder if this is really an error, or more like a warning, to make sure you dont do anything too crazy. its not a big deal for me to change it, but if the above method is actually valid, i would like to keep it that way.

**Comment by ianelliottus** [comment]
I assume that you are using the following extensions:

- Instance extensions:
  - VK_KHR_surface
  - VK_KHR_win32_surface
- Device extensions:
  - VK_KHR_swapchain

and that you are not using the VK_KHR_display or VK_KHR_display_swapchain extensions (a.k.a. the "display" extensions).  Is this correct?

Assuming that I'm correct, if you look at the bottom of sub-section "29.2.4. Win32 Platform", you'll see the following sentence:

> With Win32, minImageExtent, maxImageExtent, and currentExtent are the window size. Therefore, a swapchain’s imageExtent must match the window’s size.

This is why validation is generating the error.  The specification is saying that the following values must all be equal for Windows:

- VkSurfaceCapabilitiesKHR::currentExtent
- VkSurfaceCapabilitiesKHR::minImageExtent
- VkSurfaceCapabilitiesKHR::maxImageExtent
- VkSwapchainCreateInfoKHR::imageExtent

You mention fullscreen mode.  That's why I'm wondering if you use the "display" extensions.  What are you doing to switch between "windowed mode" and "fullscreen mode".

Of course, there may be forgiving implementations, that allow your application to operate outside the spec.

**Comment by nco2k** [comment]
sorry again, for the misunderstanding.

yes im using:

VK_KHR_surface
VK_KHR_win32_surface
VK_KHR_swapchain

and no i dont use:

VK_KHR_display
VK_KHR_display_swapchain

for fullscreen mode, i simply change the window style to borderless (WS_POPUP) and resize it. then i temporary change the desktop resolution with the winapi ChangeDisplaySettingsEx function. so yea, i dont use a real/exclusive fullscreen. i should have been clearer on that.

with my fictional example from above, the data would look as following on my gtx 1060:

VkSurfaceCapabilitiesKHR::currentExtent.width = 1280
VkSurfaceCapabilitiesKHR::currentExtent.height = 720

VkSurfaceCapabilitiesKHR::minImageExtent.width = 1
VkSurfaceCapabilitiesKHR::minImageExtent.height = 1

VkSurfaceCapabilitiesKHR::maxImageExtent.width = 32768
VkSurfaceCapabilitiesKHR::maxImageExtent.height = 32768

VkSwapchainCreateInfoKHR::imageExtent.width = 1280
VkSwapchainCreateInfoKHR::imageExtent.height = 768

my selected imageExtent is larger than currentExtent, but in the range between minImageExtent and maxImageExtent. i dont plan on drawing past the currentExtent anyway. i just want to avoid unnecessarily recreating the whole swapchain etc. if possible. but if creating a larger imageExtent could cause problems, then i will change it of course.

in my mind there are two possibilities. creating a larger imageExtent is...

A.) a total no-go and i simply got lucky.
B.) actually valid as long as you dont do anything too crazy.

**Comment by mark-lunarg** [comment]
@nco2k, the Vulkan spec says in section 30.2.4. 'Win32 Platform': "With Win32, minImageExtent, maxImageExtent, and currentExtent are the window size. Therefore, a swapchain’s imageExtent must match the window’s size."  This is what we are validating against.  If you think the spec should be changed you'd need to file an issue with in the Khronos repo Vulkan-Docs, IIRC.

**Comment by ianelliottus** [comment]
> in my mind there are two possibilities. creating a larger imageExtent is...
> 
> A.) a total no-go and i simply got lucky.

A.  You got lucky.  This is a driver bug, which will be fixed in a future release.  The cube demo (in the Vulkan SDK) has code that deals with resizing a swapchain.  To work long term, and to be portable, your application should be modified.  Since there isn't a validation-layer bug, I'm closing this issue.

Best regards,
Ian
