### ISSUE TITLE
Potentially spurious "Additional bits in Source accessMask are specified when layout is VK_IMAGE_LAYOUT_UNDEFINED" warning

### ISSUE THREAD

**Issue by aejsmith** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1533]
This is partly a query, as I'm not entirely sure whether I'm right here.

When setting oldLayout to VK_IMAGE_LAYOUT_UNDEFINED in a transition to indicate that the previous image contents need not be preserved, I get warnings like the following when setting a non-zero srcAccessMask:

> Additional bits in Source accessMask 0x400 [VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT] are specified when layout is VK_IMAGE_LAYOUT_UNDEFINED

However, I would have thought that it would still be necessary to include previous write accesses in the barrier here (despite the fact it's invalidating the previous contents) to ensure that they are flushed from caches etc. before the transition. If that's correct, then I don't think we should get a warning here.

Am I getting this right, or is it actually not necessary to include anything in srcAccessMask here?

**Comment by Tony-LunarG** [comment]
I'm guessing that this is coming from the definition of VK_IMAGE_LAYOUT_UNDEFINED in the spec:

> VK_IMAGE_LAYOUT_UNDEFINED: Supports no device access. 

There's also an example in the spec of changing the layout from PRESENT_SRC_KHR to COLOR_ATTACHMENT_OPTIMAL that says you could use an old layout of LAYOUT_UNDEFINED and it is using a srcAccessMask of 0, so that leads me to believe that 0 is acceptable for transitions away from LAYOUT_UNDEFINED.

Based on these 2 sources, I think that specifying a non-zero device access mask with an oldLayout of LAYOUT_UNDEFINED  should probably stay a warning since LAYOUT_UNDEFINED supports no device access. 

I can see some haziness about an image whose layout is undefined because it was just created vs using LAYOUT_UNDEFINED because you don't care about the contents, but the spec doesn't make such a distinction.

**Comment by Tony-LunarG** [comment]
Closing - feel free to re-open if there's still a question
