### ISSUE TITLE
DRAWSTATE_RENDERPASS_TOO_MANY_CLEAR_VALUES warning is not useful

### ISSUE THREAD

**Issue by punkUser** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1632]
This warning should probably be removed. Reasons:

1) There a many reasons that a data-driven engine will always pass a clear value array parallel to the render targets/attachments array regardless of whether any of the values are used.

2) There is nothing at all unsafe about always passing a value for each attachment and only some of them being used. Indeed this is the required behavior in cases where you want to only clear the "last" attachment.

3) Expecting the application to trim the array only from the "right" is inconsistent and pointless.

4) Per #2 above, I can't think of any non-contrived situations where this warning would catch a legitimate bug in the application.

**Comment by mark-lunarg** [comment]
@karl-lunarg, we can leave this as-is, remove it outright, change it to a perf-warning, or remove it from here and add a note to the assistance-layer tracking issue.  I prefer the latter...

**Comment by tobine** [comment]
I vote leave as-is with secondary vote being remove outright. This doesn't make much sense to me in assistance-layer. The warnings are primarily targeted at inexperienced Vulkan developers and can by ignored by developers who know there is no such issue.

This particular warning is useful for a new developer who incorrectly oversizes the clear value array. An undersized array is an error so that will be hit, but an accidental over-size would lead to strange behavior that's difficult to debug. If I remember correctly, such behavior drove the request for this warning.

**Comment by chrisforbes** [comment]
@tobine at the time, wasn't there also confusion about how the indexing worked? I think this is getting less useful over time.

**Comment by tobine** [comment]
@chrisforbes I don't recall if this specific case was one of confused indexing, although I do remember there were (are) such cases.
I'm certainly ok removing this warning.
