### ISSUE TITLE
layers: Clang 32-bit warning: stdcall calling convention ignored on variadic function

### ISSUE THREAD

**Issue by null77** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1649]
Found this while building with ANGLE/Chrome:

> C:\src\chromium\src\third_party\vulkan-validation-layers\src\include\vulkan\vk_layer.h(71,18):  error: stdcall calling convention ignored on variadic function [-Werror,-Wignored-attributes]
> typedef VkResult(VKAPI_PTR *PFN_PhysDevExt)(VkPhysicalDevice phys_device, ...);
>                  ^
> C:\src\chromium\src\third_party\vulkan-validation-layers\src\include\vulkan\vk_platform.h(53,24):  note: expanded from macro 'VKAPI_PTR'
>     #define VKAPI_PTR  VKAPI_CALL
>                        ^
> C:\src\chromium\src\third_party\vulkan-validation-layers\src\include\vulkan\vk_platform.h(52,24):  note: expanded from macro 'VKAPI_CALL'
>     #define VKAPI_CALL __stdcall
>                        ^
> 1 error generated.

Probably should be fixed at some point, if it's a real warning, but for now I can suppress this.

**Comment by nico** [comment]
The reason __stdcall is ignored on varags calls is that __stdcall is callee-cleanup, and the callee can't know how much it needs to pop for vararg calls. So if you really want this to be a vararg function, the fix is to just remove VKAPI_PTR from PFN_PhysDevExt. But if this points to some VKAPI_PTR function and you want to use __stdcall for your functions, then your function must not use varargs.

**Comment by MarkY-LunarG** [comment]
Fixed with commit db3f7b829bf5bb5e5288b48e9578663e1dfd8306.
