### ISSUE TITLE
core_validation: infinite loop on vkWaitForFences validation

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1652]
Hi,

we encountered a infinite loop on certain circumstances (that are we not sure of yet) if vkWaitForFences  gets validated.
Callstack:
- WaitForFences
- PreCallValidateWaitForFences
- VerifyQueueStateToFence
- VerifyQueueStateToSeq - recursive loop until crash

**Comment by mark-lunarg** [comment]
I am very much hoping that you will update this issue when you can pull together additional information...

**Comment by chrisforbes** [comment]
I see some of the breakage here. The simplest troublesome case I can see involves a semaphore which is signaled and then waited on in the same queue. Before the validate/update split in `VerifyQueueStateToSeq`, queue self-dependencies were benign -- by the time we considered recursing, `queue->seq == seq`, and so the recursive call would end up doing nothing. Now, because we haven't updated the queue state at all, we can get ourselves in trouble.

@TiemoJung, in lieu of a proper test case, could you dump out the queue submissions at the call to `VerifyQueueStateToFence` ?

@mark-lunarg I'm not really convinced that `VerifyQueueStateToSeq` does the right thing in general... there's something very fishy here.

**Comment by mark-lunarg** [comment]
@chrisforbes, thank you very much for the analysis.  Assigning to @tobine since he is familiar with the refactoring, and because I am an unapologetic optimist.

**Comment by TiemoJung** [comment]
Hi,

currently i can only add, that this happens if a very long submission chain is build with a lot of queue submits that are chained via semaphores and is then waited for with a single fence.
This bug only appeared as we basically added a submit for only a couple of commands, that would be normally written to a larger command buffer, as we narrowed down a bug in our code.

**Comment by chrisforbes** [comment]
Right, I'm convinced that it should always terminate as long as it doesn't blow the stack. I'll get rid of the crazy recursion depth -- it's not accomplishing anything.

**Comment by chrisforbes** [comment]
(Reassigning; I've already spent enough time thinking about this that I may as well fix it)

**Comment by chrisforbes** [comment]
@TiemoJung can you try your app with #1658?
