### ISSUE TITLE
vkGetPhysicalDevicePresentRectanglesKHX passes invalid surface handle

### ISSUE THREAD

**Issue by jschnarr-nv** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1661]
The loader seems to be missing proper handle unwrapping for VkSurfaceKHR in vkGetPhysicalDevicePresentRectanglesKHX.

With a working API, the surface handle passed by the application is different from the handle passed to the driver. With vkGetPhysicalDevicePresentRectanglesKHX the handle is invalid at the driver level and it matches the handle passed by the application.

**Comment by mark-lunarg** [comment]
@jschnarr-nv, are you running with the validation layers enabled?  I ask because if so the issue might not be related to the loader.   If you do have the layers enabled please try running without them to confirm where the issue lies.

**Comment by jschnarr-nv** [comment]
I hit this with validation layers disabled using runtime version 1.0.46.0.

**Comment by jschnarr-nv** [comment]
It looks like the issue is that vkGetInstanceProcAddr is directly returning the driver proc for vkGetPhysicalDevicePresentRectanglesKHX. I see that terminator_GetPhysicalDevicePresentRectanglesKHX exists but it is not getting called.

In loader_lookup_device_dispatch_table I see handling for several device group commands but not for vkGetPhysicalDevicePresentRectanglesKHX.

**Comment by mark-lunarg** [comment]
Looked through it this morning -- it appears that the loader does not correctly handle device extensions having APIs taking a PhysicalDevice.  I see that `vkGetPhysicalDeviceGeneratedCommandsPropertiesNVX` is similarly mishandled, though these seem to be the only two APIs that fall into this category.

**Comment by lenny-lunarg** [comment]
Sorry for the delay in getting to this, but this is now fixed in commit 69677ced237b0d6c0f651cc7a0e2a9b3c648f1dd.

The problem was actually that the instance extension dispatch table was missing any commands from device extensions. But any device command that uses a physical device as the dispatchable object is treated by the loader as an instance command. As a result, any physical device commands from device extensions weren't getting the terminator set up right, as you observed.
