### ISSUE TITLE
Multi gpu linux problem

### ISSUE THREAD

**Issue by pelelademadera** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1662]
Well, I have 2 rx480, with amdgpu-pro driver, running over gentoo linux.
Driver works well, all opengl and opencl, but vulkan have some problems with my setup.

I dont care if uses the 2 gpu or not, but when I have both connected, vulkan demos for example failed, many of them with that error

> pelo@pelo-pc ~/vulkantest/Vulkan/bin $ ./subpasses 
subpasses: /home/pelo/vulkantest/Vulkan/base/VulkanSwapChain.hpp:426: void VulkanSwapChain::create(uint32_t*, uint32_t*, bool): Assertion `!err' failed.
Abortado
pelo@pelo-pc ~/vulkantest/Vulkan/bin $ ./computecullandlod 
computecullandlod: /home/pelo/vulkantest/Vulkan/base/VulkanSwapChain.hpp:426: void VulkanSwapChain::create(uint32_t*, uint32_t*, bool): Assertion `!err' failed.
Abortado

bloom works, 
computenbody works for a while and black screen
computeparticles
computeshaders works

If I leave only one gpu connected, It works with no trouble at all.

and dota from steam dont work with the second gpu connected. same error as demos.
with one gpu works perfect.

**Comment by pelelademadera** [comment]
I add info:
Im using vulkan-loader-1.0.42.2
acording in gentoo portage.

acording to the ebuild.
src are:
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/archive/sdk-1.0.42.2.tar.gz
and compiled with X and wayland support

**Comment by lenny-lunarg** [comment]
As far as I can tell, this appears to be a driver bug. As the error message indicates, the problem is that `vkCreateSwapchainKHR` is returning the error `VK_ERROR_INITIALIZATION_FAILED`. The failure is occuring in the driver, which passes the failure to the loader in `terminator_CreateSwapchainKHR` and the loader just propagates the error back to the program.

This could still be a loader bug if the loader is passing the driver invalid inputs, but everything appears to be valid. The loader does create the `VkSurfaceKHR` that is passed to the loader within `pCreateInfo`, but everything in that structure looks correct to me.

As a result, my advice would be to report the bug to AMD. If they find that I'm wrong and this is a loader issue, then I can reopen the issue, but since the error is definitely originating in the driver I believe it's a driver issue. I did my testing with amdgpu-pro 17.10 on Ubuntu 16.04, with a pair of Radeon R9 380 cards.
