### ISSUE TITLE
loader_log's strncat calls are not safe

### ISSUE THREAD

**Issue by randomascii** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1675]
As I mentioned in this comment:

https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/879adf95044e42b78889b4345798c12adfc0a2d5#commitcomment-21786583

The use of strncat in loader_log is not safe. It is no safer than strcat. The recent change from strcat to strncat failed to improve safety.

**Comment by MarkY-LunarG** [comment]
Wouldn't simply changing `cmd_line_size` from uint32_t to size_t solve the problems?  That's only going to copy enough in until it goes negative.  No additional checking is required in the loader because strncat should perform the checks.  Correct?

The only place I could see having a real issue would be the last strncat since the first is set to the size of a stack allocated array of 512.  Shouldn't that always return a size of 512, and if so, if every item was hit prior to the last copy, the value would still be positive.

**Comment by randomascii** [comment]
Unfortunately changing from uint32_t to size_t does not help. size_t cannot go negative because it is unsigned and the wrap around will just be to a larger number. strncat will still be unbounded.

An strncat wrapper function that sanity checked the size parameter could work - some sort of helper function is probably needed to avoid excessive checks. It could even be as simple as a saturating subtract routine that doesn't let cmd_line_size wrap below zero.

Another subtle error is that cmd_line_size starts out being initialized to the size of the buffer, which implies that that many characters can be appended. That is incorrect because the buffer starts out with one character used, for the terminating zero. Therefore cmd_line_size should start out as sizeof(cmd_line_msg) - 1, or should have one subtracted from it when the zero is put in.

**Comment by MarkY-LunarG** [comment]
> An strncat wrapper function that sanity checked the size parameter could work - some sort of helper function is probably needed to avoid excessive checks. It could even be as simple as a saturating subtract routine that doesn't let cmd_line_size wrap below zero.

Isn't that what strncat is supposed to do itself?  (Albeit, not accounting for the null-terminator).

Looking at the [strncat man page](https://linux.die.net/man/3/strncat), it seems to indicate that it's only adding up to the length provided or the first null-terminator (which ever occurs first).  I can see how we could overwrite the null-terminator on the original string because I was missing the -1 (as you suggested), but I'm still unclear why the other check could trigger a wrap issue in this scenario.  Are you saying that implementations of strncat are insufficient?

Again, looking at the newly added code, I see a max of 37 characters out of 512 being used (that's including the null-terminator) prior to the last strncat.  So the value of cmd_line_size will always be positive.  I could make the following changes for the last strncat:

```
    if (0 < cmd_line_size) {
        // If the message is too long, trim it down
        if (strlen(msg) > cmd_line_size) {
            msg[cmd_line_size - 1] = '\0';
        }
        strncat(cmd_line_msg, msg, cmd_line_size);
    } else {
        // Shouldn't get here, but check to make sure if we've already overrun
        // the string boundary
        assert(false);
    }
```
Which would be basically boiler-plating with the addition of the -1 to the original size.

Right?

**Comment by randomascii** [comment]
> Isn't that what strncat is supposed to do itself?

strncat will ensure that you never append more characters than the size parameter passed in. But the code currently passes in incorrect size parameters. strncat can't help with that.

> Are you saying that implementations of strncat are insufficient?

Yes, because it is being used incorrectly.

> Again, looking at the newly added code, I see a max of 37
> characters out of 512 being used (that's including the
> null-terminator) prior to the last strncat. 

I can believe that. In which case this code will never misbehave. But this also means that using strncat instead of strcat (except for the last usage) is pure security theater. It adds precisely nothing because strncat is being used incorrectly and actually does virtually nothing to prevent overruns.

Here is some sample code that demonstrates the two bugs - the incorrect initial value of cmd_line_size and the problems with unconditionally subtracting from cmd_line_size. The first leads to a one-byte overrun. The second leads to arbitrarily large overruns.


// Needed for VC++ to avoid fatal warnings
#define _CRT_SECURE_NO_WARNINGS

#include <stdio.h>
#include <string.h>

struct buffers
{
	char buffer1[5];
	char buffer2[95];
};

int main()
{
	buffers a;
	size_t buf_size = sizeof(a.buffer1);
	a.buffer1[0] = 0;

	strncat(a.buffer1, "house", buf_size);
	// This prints 'house', despite the fact that it can't fit in a five character
	// buffer, due to an off-by-one error in initalizing buf_size.
	printf("%s\n", a.buffer1);

	// Correctly initialize buf_size
	buf_size = sizeof(a.buffer1) - 1;
	a.buffer1[0] = 0;

	strncat(a.buffer1, "house", buf_size);
	buf_size -= 5;
	// This prints 'hous', which is correct.
	printf("%s\n", a.buffer1);

	strncat(a.buffer1, "cat", buf_size);
	buf_size -= 3;
	// This prints 'houscat', which is incorrect.
	printf("%s\n", a.buffer1);

	strncat(a.buffer1, "dog", buf_size);
	buf_size -= 3;
	// This prints 'houscatdog', which is incorrect.
	printf("%s\n", a.buffer1);

	return 0;
}

**Comment by MarkY-LunarG** [comment]
I am not seeing the behavior you're talking about here:
> strncat(a.buffer1, "house", buf_size);
buf_size -= 5;
// This prints 'hous', which is correct.
printf("%s\n", a.buffer1);

If I do this:
```
    cmd_line_msg[0] = '\0';
    cmd_line_size -= 1;
    strncat(cmd_line_msg, "INFO", cmd_line_size);
    cmd_line_size -= 4;
```
I correctly get "INFO" printed out.  Additionally, if I concatenate the messages, they still appear correct.

```
    strncat(cmd_line_msg, ": ", cmd_line_size);
    cmd_line_size -= 2;
    if (strlen(msg) > cmd_line_size) {
        msg[cmd_line_size - 1] = '\0';
    }
    strncat(cmd_line_msg, msg, cmd_line_size);
```

For example: 
```
INFO: Found ICD manifest file /usr/local/share//vulkan/icd.d/intel_icd.x86_64.json, version "1.0.0"
```

**Comment by randomascii** [comment]
In your first example with "INFO" I agree that that code will work fine. However any *subsequent* use of that strncat pattern will fail, because (assuming a four-byte buffer)  that code leaves cmd_line_size set to 0xFFFFFFFF, meaning that subsequent calls to strncat are unbounded.

Now I know that you'll say that having a four-byte buffer is the problem. Sure. But my point is that your use of strncat is almost identical to using strcat. Your use of strncat will avoid buffer overruns only if the buffer overrun is the very last use of strncat. All previous uses could be strcat and it would make no difference.

The code's use of strncat is (with the exception of the last strncat call) security theater.

**Comment by lenny-lunarg** [comment]
I see two basic claims that you're making:
1. The code could create a buffer overflow
2. The calls to `strncat` add very little, compared to calling `strcat` instead

On the first issue, I disagree. Provided that the buffer `cmd_line_msg` is larger than about 40 bytes (the length of all of the strings, combined), there is no way that this could overflow. Since the buffer is 512 bytes and this value is not programmable, this isn't possible. It might be useful to put a comment where the buffer is declared to prevent anyone from shrinking the buffer, but no overflow can occur unless someone changes the code manually (and all code can be made unsafe if someone changes it).

I do agree with your second point. With the exception of the last call to `strncat`:

```c
strncat(cmd_line_msg, msg, cmd_line_size);
```

 there is no benefit to using `strncat` the current way. Because the buffer is large enough that there can't be an overflow, it shouldn't matter, but if the buffer was small enough for an overflow, the fact that `cmd_line_size` is being decreased by more than one means that it could overshoot zero and underflow. This would corrupt all of the checks after that. It could be fixed by keeping `strncpy` and changing the lines that decrease the value of `cmd_line_size` to something like:

```c
cmd_line_size = cmd_line_size - 5 < cmd_line_size ? cmd_line_size - 5 : 0;
```

Personally, I'd rather simply enforce safety by ensuring that the buffer is large enough in the first place, since adding checks like above won't add anything when the buffer size is 512.

**Comment by randomascii** [comment]
I'm glad we are in agreement, more or less.

I'd say that the calls to strncat (with the exception of the last one) currently add nothing, rather than very little, but that's just quibbling. I am philosophically opposed to using strncat in such a way, but not opposed enough to create a PR to use strncat 'safely' (such that the code work regardless of buffer size), so I'll shut up now.
