### ISSUE TITLE
Remove remaining husk of Swapchain layer

### ISSUE THREAD

**Issue by chrisforbes** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1683]
The meat of this layer moved to CV long ago.

**Comment by krOoze** [comment]
#1738 and #1727 also remove from `swapchain` layer.
Not much more to go...

**Comment by mark-lunarg** [comment]
@chrisforbes, if this is in progress please let me know.  I'd rather kill this layer than to update the procmap stuff, if that's alright.

**Comment by MarkY-LunarG** [comment]
We really can't just remove a layer anymore, can we?  I thought this was something Karl brought up, if an application calls an old loader and attempts to use VK_LUNARG_standard_validation, it will look for this layer because that was hard-coded in the older layer.  So, we need to keep a stub around just for that.  We can remove it from the new VK_LUNARG_standard_validation.json files, though.  That will mean future people won't load it with their newer loaders.

**Comment by mark-lunarg** [comment]
I don't see why swapchain is materially any different than mem_tracker, shader_checker, device_limits, image, draw_state, or param_checker.

**Comment by chrisforbes** [comment]
This is only a problem if people are mixing loader & bundled layers from different sources. This shouldn't really happen. Would be different if we were talking about breaking third-party layers.
