### ISSUE TITLE
vkGetDeviceProcAddr, when hooked, does not always get used to fill in extension function pointers in the dispatch table

### ISSUE THREAD

**Issue by nvining-work** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1693]
Summary: If your capture layer hooks vkGetDeviceProcAddr() using the layer JSON, and does *not* return a pointer to itself when asked for the address of "vkGetDeviceProcAddr", it will not be used to load the device dispatch table from layer_init_device_dispatch_table(). In fact, vkGetDeviceProcAddr() will never be hit when filling the device dispatch table for device extensions from the loader.

I found this when writing a new layer; I used the example from the SDK as a base point, but renamed vkGetDeviceProcAddr to Intercept_vkGetDeviceProcAddr and referenced it in the JSON. My understanding is that this *should* be put after the trampoline function and used every time we create a device. In practice, when filling in the dispatch table in layer_init_device_dispatch_table() after creating the device, only the core extensions call Intercept_vkGetDeviceProcAddr(). The extensions do not, and therefore I get no opportunity to hook them. This was the cause of much mystery.

I am happy to write a minimal test case if desired, but I'm not certain how to fix the dispatcher logic in this case. This seems to be a bug, or at the very least weird and inconsistent behaviour - either both the device extensions and the core functions should fail to use my layer's vkGetDeviceProcAddr(), or neither of them should work.

**Comment by MarkY-LunarG** [comment]
I looked at several of our layers, and we always return a pointer to the internal GetXXProcAddr call inside itself.  For example, layers/core_validation, layers/object_tracker, layers/swapchain all intercept vkGetDeviceProcAddr and return their internal function.  You need that because an application could query "vkGetDeviceProcAddr" and your layer might be the first in the device call-chain.

That being said, I looked and the code in the loader, and it appears to indicate if you provided the GetDeviceProcAddr in the JSON it should use it.  The loader code for this is in loader/loader.c.   The two places to look are:
 1. Setup of the layers override GetDeviceProcAddr from JSON file is at approximately line 2066.  The name of the override function is written to `str_gdpa` in the layer properties.
 2. Setup of the layer properties in the loader occurs arround line 4126.  You should see the following line:

```
if (strlen(layer_prop->functions.str_gdpa) == 0) {
    fpGDPA = (PFN_vkGetDeviceProcAddr)loader_platform_get_proc_address(lib_handle, "vkGetDeviceProcAddr");
    layer_prop->functions.get_device_proc_addr = fpGDPA;
} else
    fpGDPA =
        (PFN_vkGetDeviceProcAddr)loader_platform_get_proc_address(lib_handle, layer_prop->functions.str_gdpa);
```

Thus, if it didn't find the str_gdpa from before, it should go down the "vkGetDeviceProcAddr" query path.

Can you provide an example (JSON, and source)?

**Comment by nvining-work** [comment]
I've put together a repro case, and it's just getting checked over by a second set of eyes. Once that's done, I'll put it up here.

**Comment by nvining-work** [comment]
Attached. FYI someone else in the team hit the same issue over here with vkGetInstanceProcAddr() and vkCreateXcbSurfaceKHR not being hooked correctly unless we made the same change.

[test_case_layer3.tar.gz](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/files/976675/test_case_layer3.tar.gz)

**Comment by MarkY-LunarG** [comment]
Thanks, I'll take a look at it today.

**Comment by MarkY-LunarG** [comment]
Commit 2bf5906ac1244fc9ab9b294845f59c0b51389f44 should fix your issues with the loader.

As a word of caution, I still believe that you need to at least expose "vkGetDeviceProcAddr" from your vkGetInstanceProcAddr call because a layer above yours may call that.  A layer should use the chain info passed to it during vkCreateDevice, but I don't think we can guarantee that will be the case. I checked, and the validation layers don't appear to do that, but it's still a valid call.

**Comment by nvining-work** [comment]
Marvelous. Thanks - and yeah, that one makes sense, just not the "I have to hook myself" bit. :)
