### ISSUE TITLE
Performance hint: Warn if application does not use pipeline cache

### ISSUE THREAD

**Issue by hesiod** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1696]
Since providing a pipeline cache should almost always [1] provide a net win to the application, it might be useful if a validation layer provided a performance hint if the application does not provide a pipeline cache when creating pipelines. Even without persistent storage, the application could just provide a memory-only cache.

[1] And that's the caveat with such a suggestion, I guess memory/storage-constrained applications might actively choose not to use pipeline caches.

**Comment by TobiasHector** [comment]
> [1] And that's the caveat with such a suggestion, I guess memory/storage-constrained applications might actively choose not to use pipeline caches.

Is this based on any vendor recommendations? The pipeline cache should *reduce* memory consumption, not increase it. I can't categorically say it *never* increases memory (trivially - create 0 pipelines and it obviously has), but the idea is to avoid creating the same shader binaries multiple times - which is what happens if you don't use a pipeline cache - each new binary would take up more memory. Pipeline caches provide the opportunity for that binary data to be created/allocated just once and then just referenced multiple times, which should be a big net win.

All performance warnings that could go into such a layer are generalizations anyway; even vendor specific recommendations are of this nature, because they're *always* corner cases. But this is why they should be *warnings* not *errors*.

Also, this should probably reference #1612 - which is where discussion of a layer to handle perf warnings is taking place. CC @mark-lunarg @karl-lunarg

**Comment by hesiod** [comment]
@TobiasHector: No, that caveat is just my own wild guess. I would say that pipeline caches *should* always provide a net win, but as you say, there corner cases are always a possibility. (What I had in mind is an application that during its lifetime only uses a few pipelines, does not reuse a shader in another pipeline and is memory-constrained in a way that the few extra kB make a difference - but I'm not sure whether that is realistic.)

**Comment by mark-lunarg** [comment]
@hesiod -- thanks for the suggestion -- I've added it to the placeholder issue #1612, and will close this as it is referenced there.

**Comment by mark-lunarg** [comment]
This check is now available in the Assistant Layer, hosted in the [Github VulkanTools repository](https://github.com/LunarG/VulkanTools), and soon to be available in the Vulkan SDK.
