### ISSUE TITLE
Layers: Stencil-only image layout tracked incorrectly

### ISSUE THREAD

**Issue by MaciejJesionowskiAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1700]
I'm getting the following error:

> DS(ERROR): object: 0x28a4e61acd0 type: 6 location: 1938 msgCode: 6: Cannot submit cmd buffer using image (0x28a4eabb8d0) [sub-resource: aspectMask 0x2 array layer 0, mip level 0], with layout VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL when first use is VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL.

Which I think may be caused by this code (SetImageLayout function in buffer_validation.cpp):
```
// TODO: If ImageView was created with depth or stencil, transition both layouts as the aspectMask is ignored and both
// are used. Verify that the extra implicit layout is OK for descriptor set layout validation
if (image_subresource_range.aspectMask & (VK_IMAGE_ASPECT_DEPTH_BIT | VK_IMAGE_ASPECT_STENCIL_BIT)) {
    if (FormatIsDepthAndStencil(image_state->createInfo.format)) {
        sub.aspectMask |= (VK_IMAGE_ASPECT_DEPTH_BIT | VK_IMAGE_ASPECT_STENCIL_BIT);
    }
}
```

When an error is generated the `cb_image_data` seems to have aspect mask = 0x2 (DEPTH) which is incorrect because I only use STENCIL in my code (0x4).

**Comment by tobine** [comment]
Do you have a repo?
Does the image have a depth component?
Do you transition the stencil aspect from VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL to VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL?

Note that the code that transitions depth and stencil aspects is intentional, even if only a single aspect it used. The depth and stencil aspects should both be set for DS images and they should both be transitioned as well.
If you're correctly transitioning the stencil aspect, then there may be a validation bug that's not correctly transitioning the depth aspect.

**Comment by MaciejJesionowskiAMD** [comment]
You're right, I was using mixed depth/stencil format, even though only stencil was in active use. The barriers should use both aspect flags and that was the source of an error.

Thanks!
