### ISSUE TITLE
Is static-linking the loader itself possible?

### ISSUE THREAD

**Issue by gigadude** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1707]
It looks like VKstatic.1.lib (on Windows) is a statically-linkable version of the loader, is its use documented anywhere? Specifically what happens if I statically link the loader into a 3rd-party .dll which a an app may be using in conjunction with newer versions of vulkan-1.dll?

**Comment by lenny-lunarg** [comment]
Like you said, `VKstatic.1.lib` is a statically linkable version of the Vulkan loader. Unfortunately, we don't have much documentation on the static version of the loader. This is because in general it's far better to use the dynamic loader. The dynamic loader will find new extensions as they are released, and will get bug fixes over time. On top of that, Vulkan compatible drivers install the dynamic loader onto people's systems, so you can count on it being there as long as the drivers support Vulkan.

But to answer your immediate question, I would not expect good things to happen if you have a program that ends up linking to both the static and dynamic loaders. I just tried it out and it seems to work for a very simple case, but I would expect trouble in more complicated cases. The reason it compiles is that the Vulkan symbols do not get exported by the dll, since they aren't compiled with `declspec(dllexport)`, so the final app only links to the dynamic loader, while the new dll only links to the static loader. But problems would arise if your dll and the final app try to pass any Vulkan objects back and forth. If you do that, you may end up with two different loader versions, which will mean that the implementation of those objects would be different between your dll and the app. As a result, I __think__ that you could do what you're suggesting as long as your dll doesn't transmit any Vulkan objects to the app. If it does pass Vulkan objects to the app, then you'd need to make sure you only link to one Vulkan loader (which I would strongly recommend doing anyway). If you do want to include a specific version of Vulkan with your loader, you could always try linking Vulkan in statically, but exporting the Vulkan symbols with `__declspec(dllexport)` so that the final app can get Vulkan from your dll, but to do that you'd have to play around with build options to get it working. In general, though, I'd definitely recommend just sticking to the dynamic loader.

**Comment by gigadude** [comment]
Thanks for the info, I ended up dynamically loading the vulkan-1.dll myself. We have a situation where a client dll supports multiple APIs and we don't want to force an app which is not using Vulkan to require the loader dll. It would be nice if there was a statically-linked shim version of vulkan-1.lib which dynamically loaded the newest compatible vulkan-1.dll on first use.

**Comment by lenny-lunarg** [comment]
Generally, the idea is that `vulkan-1.dll` is already supposed to be the component that's responsible for loading the Vulkan functions, so adding another library into the process would be redundant. If you want to dynamically load `vulkan-1.dll`, you can do that, you'd just have to manually load each function's address as [described here](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/loader/LoaderAndLayerInterface.md#indirectly-linking-to-the-loader).

On top of that, there isn't actually any requirement for a computer to support Vulkan for the loader to be present. If a computer does not support Vulkan, then Vulkan functions will just return error codes. I can't remember off the top of my head exactly what will and won't work, but I know you'll never get any physical devices. This means you could just include `vulkan-1.dll` with your product, but recognize that if the functions fail then Vulkan isn't supported.

Also, I've added some documentation [here](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/loader/LoaderAndLayerInterface.md#directly-linking-to-the-loader) since you did point out that the static loader documentation was seriously lacking. That documentation should make it into our next SDK release. I'm going to close the issue now, since I think your questions have been answered and since I've improved the documentation. If you do have more questions, feel free to ask.
