### ISSUE TITLE
Why is VulkanRT installer size large, and could it be reduced?

### ISSUE THREAD

**Issue by jjulianoatnv** [KhronosGroup/Vulkan-LoaderAndValidationLayers#172]
The VulkanRT installer is a little under 13 MB in size. It gets included in the SDK installer, in IHV display driver packages, and (optionally) in ISV apps. There has been concern about adding such a large thing to my IHV display driver package. This issue explores the VulkanRT installer size.

I asked @davidlunarg if the VulkanRT installer would be considerably smaller if the GUI were removed from it. I'll let him respond into this issue instead of pasting his email here without having asked first. In short, the GUI portion is insignificant, and over 99% of the size of the VulkanRT installer is the footprint of the embedded 32-bit plus 64-bit MSVC 2013 redistributables.

My IHV driver already includes the MSVC 2013 redist for a different purpose. The copy inside the VulkanRT installer is a 2nd copy of the redist files.  Other IHVs and apps might be in a similar situation.

I'm not aware of any scenarios where an end user directly installs the VulkanRT using the VulkanRT installer. For all scenarios I'm aware of the VulkanRT installer is embedded into some other installer. Therefore I wonder if it makes sense to remove the redist from the VulkanRT installer.

## Proposal
* Remove the redist from the VulkanRT installer
* Document that that an installer which embeds the VulkanRT installer must first install a compatible MSVC 2013 Redistributable
* Document that a user who runs the VulkanRT installer directly must first install a compatible MSVC 2013 Redistributable
* Modify the VulkanRT installer to intentionally fail (with a non-zero exitstatus less than 10) if it cannot determine that the redist is already installed.

The Vulkan SDK and IHV drivers and ISV apps would all install the redist themselves before installing the VulkanRT installer.

**Comment by davidlunarg** [comment]
Jeff is right about the MSVC redistributables being the lion's share of the size of the Runtime installer. I  just did a quick test build of the installer without the redistributes and the size went down from 13.3Mb to 281k. I would ask, though, how much is 13Mb in an installer that is 308Mb (the latest nVidia driver I have) or  184Mb (the latest Intel driver I have). I like the control of making sure that the software the Runtime depends on is installed, and should the dependency change to some other version of the redistributables, I know that the new version will be there because my installer installed it and don't have to depend on a driver update to put the new redistributables on the system. Errorring out of the RT installer will be a bad user experience during an SDK install (which installs the RT).

**Comment by jjulianoatnv** [comment]
The addition of 13MB was noticed. 13MB of redundant data is meaningful.

I don't see redist version as a problem. The SDK would install the required version of redist for the RT version that is packaged in the SDK. LunarG builds the RT and the SDK, and chooses which RT is packaged in the SDK.

If a new version of the RT requires a new MSVC redist then my own driver package would not adopt the newer RT unless it also installs the newer redist.

Comparing to linux, if the Windows platform had a real package manager like exists for linux distributions then it would be the job of the package manager to satisfy the RT's requirement that the redist be present, and it would be the package manager that installs the redist on behalf of all packages that depend on it.  The cygwin installer is an example of an actual package manager on the Windows platform. Others probably exist.

In the absence of a real package manager I don't think the RT should default to embedding its own redist dependency because the RT is itself always embedded into something else. It therefore should be the something else's responsibility to satisfy the dependency. That enables the something else to manage the dependency and avoid redundant copies of the redist.

Back to my original assumption: does there exist a valid use case where an end user installs the VulkanRT directly?  Or is it always embedded into something else: SDK, IHV driver, ISV app.

**Comment by davidlunarg** [comment]
Including this from an email from Piotr Bialecki at Intel for completeness of this issue:

> We can live without MSVC included in VulkanRT, however, we prefer to leave it where it is. It is cleaner and easier to maintain when the VulkanRT installer ensures all components it requires. Besides, 13 MB is not much in comparison to the total driver size.

> I think it is worth to consider another, compromise solution: remove MSVC dlls installation from VulkanRT and link MSVC into VulkanRT binaries statically. It probably could reduce VulkanRT size significantly and still IHVs and end users would not have to install MSVC on their own.

**Comment by davidlunarg** [comment]
Scenario where it would be desirable for the VulkanRT to be independent of an IHV/ISV release:

A Vulkan RT is released. It does not have MSVC redist in it. An IHV releases a driver with that RT in it, including the appropriate MSVC redist. A bug is found in the Vulkan Loader, and the RT must be turned. In order to fix the bug, a different version of MSVS must be used, requiring a different MSVC redist be installed on the system. In order for a proper, working fix of the RT to make it out to users, all IHVs would have to re-release their driver installers that would include the new RT and new redist. Releasing the RT via IHVs slows down the speed at which the new RT would be made available to end users.

**Comment by davidlunarg** [comment]
I should have mentioned in my previous comments that even though removing the redistributes might inconvenience whoever is releasing the Vulkan Runtime Installer in the future, LunarG is willing to remove them from the next release of the Runtime if that is what is agreed to here in this discussion.

**Comment by davidlunarg** [comment]
@jjulianoatnv has reported a problem in which the Vulkan Runtime installer being run on a certain hardware configuration is taking 10 seconds to run in silent mode when the MSVC redistributables are already on the system, and greater than a minute when when they are not. In order to reduce these times (by not installing the redist at all, and by reducing the footprint of the RT installer because the redistributables are not present), I'm considering removing the MSVC redist from the RT installer. Before I do, however, I would like to hear from the IHVs that this is OK with them, because the IHVs' installers may potentially need to be modified to include the redist, and install them before invoking the Vulkan RT installer. Please respond to this issue to register your approval or disapproval.

**Comment by davidlunarg** [comment]
It looks like it will work to change the loader to static link the MSVC libraries, eliminating the need for the Runtime Installer to install the MSVC redistributables. We should be able to get this change into the next SDK release. The Vulkan SDK Installer will be modified to install the MSVC redistributables because they are still needed by the SDK. IHVs whose drivers have a dependency on the MSVC redistributables should install them because the Vulkan Runtime will no longer install them.

Initial experiments indicate that the size of the RT installer can be reduced from about 13 Mbytes to about 600 Kbytes.

**Comment by hlandau** [comment]
Another option would be to link to msvcrt.dll instead. This can be done by using a mingw toolchain, or, IIRC, building using the Windows Driver Development Kit instead of Visual Studio.

**Comment by davidlunarg** [comment]
MSVC redistributables have been removed from the Vulkan Runtime Installer. This change will be in the next release of the Vulkan SDK.

**Comment by jjulianoatnv** [comment]
Thank you.
