### ISSUE TITLE
loader: crashes with combination of implicit overlay layer and explicit layers

### ISSUE THREAD

**Issue by jon-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#20]
Here is the description of crash from Pierre-Loup at Valve.

"Correct, my setup was that all the DSOs and JSON manifest files from the validation layers were installed in /etc/vulkan/explicit_layers.d, and the Steam overlay setup was in place with the implicit layer. The overlay worked fine and the implicit layer was getting loaded, but trying to activate any additional layers through the environment from that selection of available explicit layers would crash the loader. "

The overlay layer should be the same (or similiar) to the one in LunarG VulkanSamples repo.

**Comment by karl-lunarg** [comment]
We had a similar problem in the screenshot object.  When a layer creates a dispatchable object like a command buffer, the create step does not pass through the API binding code in trampoline.c, where that code copies the device dispatch table pointer into the newly-created (dispatchable) command buffer object.   Since the layer doesn't go through trampoline, the dispatch table is left out of the new command buffer object, causing subsequent dispatching attempts to fail.

We're solving this for now in the same way as in screenshot by copying the dispatch table pointer into the very start of the (opaque) cmd buffer object, which is a bit ugly.  We need to come up with a better-architected way to do this.  But luckily this issue is confined only to layer implementations.

I suspect that this problem showed up only now because when the overlay layer is set up as an implicit layer, it is loaded first.  Other testing probably loaded it last, where the cmd buffer didn't have to be dispatched to another layer.

In this case, the reported crash wasn't in the loader; it was in the layer after the overlay layer.  Note that while this fix fixes the overlay sample in the LunarG Samples repo, other overlay layer implementations will have to apply their own similar fixes.
