### ISSUE TITLE
VK_ERROR_OUT_OF_HOST_MEMORY when extent is not specified for vkCreateSwapchainKHR

### ISSUE THREAD

**Issue by quixoticaxis** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2035]
I'm new to Vulkan API and I was going through [Vulkan Tutorial](https://vulkan-tutorial.com/Drawing_a_triangle/Presentation/Swap_chain). In order to show how validation layers can help, the author recommends:
> Try removing the createInfo.imageExtent = extent; line with validation layers enabled. You'll see that one of the validation layers immediately catches the mistake and a helpful message is printed

but when I do not specify extent for vkCreateswapchainKHR, the call fails with
> validation layer: vkCreateSwapchainKHR: returned VK_ERROR_OUT_OF_HOST_MEMORY, indicating that a host memory allocation has failed

instead of notifying me that I use some extent not equal to current.

I'm using Windows 10 Enterprise on i5 6600 without dedicated GPU.

**Comment by quixoticaxis** [comment]
Do you need any additional info from me?

**Comment by mark-lunarg** [comment]
@quixoticaxis, this should be OK for now -- we use the <incomplete> label for validation holes, i.e., the _validation_ is incomplete.  Outside of bugs these get the highest priority.

**Comment by jzulauf-lunarg** [comment]
Investigating the issue. quixoticaxis -- if you are using an SDK can you let me know the version.  (or if you've built the layers from source, let me know the commit ID).  I've identified an issue fixed in 1.0.57 (and present in several prior revisions) that would have the symptoms you describe.  

With this fix (assuming I'm correct) you would still potentially see the VK_ERROR_OUT_OF_HOST_MEMORY (depending on the initialized values in the imageExtent field), but an additional message identifying the invalid values would also be generated prior to the out of memory message.

**Comment by quixoticaxis** [comment]
At the time I've submitted this issue I was using 1.0.51.0.

**Comment by jzulauf-lunarg** [comment]
That's consistent with what I'm seeing.  In 1.0.51.0, the parameter check was being masked. Can you retest with 1.0.57.0 or 1.0.16.1?

**Comment by quixoticaxis** [comment]
Everything is fine on 1.0.61.1, now I get "vkCreateSwapChainKHR() called with imageExtent = (0,0), which is outside the bounds..."
Looks good ^-^

**Comment by jzulauf-lunarg** [comment]
Fixed in 1.0.57.0. Closing.
