### ISSUE TITLE
Invalid DisplayKHR Object

### ISSUE THREAD

**Issue by kristan2016** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2050]
When I enabled the layer named "VK_LAYER_LUNARG_standard_validation", the ObjectTracker reported  the error information as below:
```
* ERROR: [ObjectTracker] Code 696279041 : Invalid DisplayKHR Object 0x214b070. The spec valid usage text states 'display must be a valid VkDisplayKHR handle' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkGetDisplayModePropertiesKHR-display-parameter)
```
and then the application crashed.
After If I disabled the layer "VK_LAYER_LUNARG_standard_validation", the application executed successfully.

**Comment by courtney-g** [comment]
I recommend you check your use of DisplayKHR objects. Just because an application works, doesn't mean that it is free of issues.
If you set up a VkDebugReport object you could set a breakpoint in your callback and see where the layers think there is an issue. Hopefully that will help you isolate the problem or put together a bug report for the validation layers.

**Comment by mark-lunarg** [comment]
Closing this for now as there is no action required.  @kristan2016, if you find an issue with the layers or the loader please reopen this issue.  Good luck with your application.
