### ISSUE TITLE
Filtering extensions, NVidia 385.41 and VK_KH(R/X)_external_memory_capabilities

### ISSUE THREAD

**Issue by kalmiya** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2051]
Afaik recently VK_KHX_external_memory_capabilities was 'promoted' to VK_KHR_external_memory_capabilities.  

As a result NVidia updated their graphics driver to 385.41, so what I see is our game won't find "VK_KHX_external_memory_capabilities" anymore ( which is required by the Oculus 1.17 SDK) and it crashes. 
At the same time Oculus - depending on that extension - needed to update their SDK. Which they did in the 1.18 SDK (it adds two functions to query required extensions and then switches to VK_KHR_external_memory_capabilities).

But NVidia is bundling their 385.41 gfx-driver with an older vulkan-runtime (49 I think), meaning VK_KHR_external_memory_capabilities isn't available either, because the vulkan-loader filters out unknown extensions!

Worse, if you happen to have the the latest LunarG SDK installed (as most developers will have), it actually does work, because then it appears to prefer that vulkan-loader, so everything will work for developers and the problems will appear the moment you release your product to customers ( who only have the nvidia-driver installed - but not the LunarG SDK ). Workaround is to - on init of you application - set the VK_LOADER_DISABLE_INST_EXT_FILTER environment variable with putenv().

I'm wondering what the reason is for filtering of the available extensions by the vulkan-loader ? Isn't the idea that the loader can support newer extensions - without knowing what future drivers are providing ?
So isn't the more sensible default to _not_ filter ?

**Comment by courtney-g** [comment]
Only Instance extensions are filtered. That's because instance extensions generally need help from the loader to do what's needed. E.g. an instance extension could operate on all devices. Where is the code to iterate over all devices? Only place is the loader.

**Comment by lenny-lunarg** [comment]
Like @courtney-g said, instance extensions don't work without loader support because there's no way to automatically figure out how to reconcile the different physical devices. The theory behind these extensions was that KHX extensions were experimental extensions that should not be used in production code, so no one should ship anything that uses them. But people used KHX extensions in production code anyway, so we wound up with a situation where people had shipped software that depended on extensions that we knew we were going to remove.

If you need to guarantee that people have an up to date runtime, the only way you can do so is to bundle the loader (either by packaging the runtime or by including the loader library file) with your program.

**Comment by lenny-lunarg** [comment]
Did this help you out? If there's nothing else to add here, then I'd like to close the issue.

**Comment by kalmiya** [comment]
Yes, thanks - the explanation was really helpful. 
This issue can be closed.
