### ISSUE TITLE
[Help] How to fix the `descriptor not accessible from stage` error ?

### ISSUE THREAD

**Issue by linuxaged** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2099]
The error says:

	Error: [SC] Code 14 : Shader uses descriptor slot 0.0
	(used as type `ptr to const uniform sampler+image(dim=1, sampled=1)`) 
	but descriptor not accessible from stage VK_SHADER_STAGE_FRAGMENT_BIT

If I get it correctly, this error means `VkDescriptorSetLayoutBinding.stageFlags` does not match `VkPipelineShaderStageCreateInfo.stage`. But I am sure both of them were set to `VK_SHADER_STAGE_FRAGMENT_BIT` in my code.

Here is my GLES 3.1 shader, the uniform sampler here is `u_diffuse`

    #version 310 es
    #extension GL_ARB_enhanced_layouts : enable
    precision highp float;
    precision highp int;
    layout( location = 0 ) out vec4 v_fragColor ;
    layout( location = 2 ) uniform sampler2D u_diffuse ;
    layout( location = 1 ) in vec3 v_normal ;
    layout( location = 0 ) in vec3 v_position ;
    layout( location = 2 ) in vec2 v_texcoord0 ;
    void main (void) {
        vec4 color =vec4(0., 0., 0., 0.) ;
        vec4 diffuse =vec4(0., 0., 0., 1.) ;
        diffuse = texture (u_diffuse, v_texcoord0) ;
        color.xyz +=diffuse.xyz ;
        color =vec4(color.rgb * diffuse.a, diffuse.a) ;
        v_fragColor = color ;
    }

    #version 310 es
    #extension GL_EXT_shader_io_blocks : enable
    #extension GL_ARB_enhanced_layouts : enable
    precision highp float;
    precision highp int;
    out gl_PerVertex { vec4 gl_Position; };
    layout( std140, binding = 0 ) uniform modelUniformBuffer 
    {
        layout(offset = 0) mat4 u_modelMatrix;
        layout(offset = 64) mat4 u_modelInverseMatrix;
    };
    layout( std140, binding = 1 ) uniform viewProjectionUniformBuffer 
    {
        layout(offset = 0) mat4 u_viewMatrix;
        layout(offset = 64) mat4 u_viewInverseMatrix;
        layout(offset = 128) mat4 u_projectionMatrix;
        layout(offset = 192) mat4 u_projectionInverseMatrix;
    };
    layout( location = 1 ) in vec3 a_normal ;
    layout( location = 1 ) out vec3 v_normal ;
    layout( location = 0 ) in vec3 a_position ;
    layout( location = 0 ) out vec3 v_position ;
    layout( location = 2 ) in vec2 a_texcoord0 ;
    layout( location = 2 ) out vec2 v_texcoord0 ;
    void main (void) {
        vec4 pos = u_viewMatrix * u_modelMatrix * vec4 ( a_position, 1.0 ) ;
        v_normal = transpose( mat3( u_viewInverseMatrix ) ) * transpose( mat3( u_modelInverseMatrix ) ) * a_normal;
        v_texcoord0 =a_texcoord0 ;
        gl_Position =u_projectionMatrix * pos ;
    }

**Comment by chrisforbes** [comment]
u_diffuse should be declared with the 'binding' layout qualifier, not
'location'. The location qualifier there does nothing.

On Oct 3, 2017 03:45, "Tracy Ma" <notifications@github.com> wrote:

The error says:

Error: [SC] Code 14 : Shader uses descriptor slot 0.0
(used as type `ptr to const uniform sampler+image(dim=1, sampled=1)`)
but descriptor not accessible from stage VK_SHADER_STAGE_FRAGMENT_BIT

If I get it correctly, this error means VkDescriptorSetLayoutBinding.
stageFlags does not match VkPipelineShaderStageCreateInfo.stage. But I am
sure both of them are set to VK_SHADER_STAGE_FRAGMENT_BIT in my code.

Here is my GLES 3.1 shader, the uniform sampler here is u_diffuse

#version 310 es
#extension GL_ARB_enhanced_layouts : enable
precision highp float;
precision highp int;
layout( location = 0 ) out vec4 v_fragColor ;
layout( location = 2 ) uniform sampler2D u_diffuse ;
layout( location = 1 ) in vec3 v_normal ;
layout( location = 0 ) in vec3 v_position ;
layout( location = 2 ) in vec2 v_texcoord0 ;
void main (void) {
    vec4 color =vec4(0., 0., 0., 0.) ;
    vec4 diffuse =vec4(0., 0., 0., 1.) ;
    diffuse = texture (u_diffuse, v_texcoord0) ;
    color.xyz +=diffuse.xyz ;
    color =vec4(color.rgb * diffuse.a, diffuse.a) ;
    v_fragColor = color ;
}

#version 310 es
#extension GL_EXT_shader_io_blocks : enable
#extension GL_ARB_enhanced_layouts : enable
precision highp float;
precision highp int;
out gl_PerVertex { vec4 gl_Position; };
layout( std140, binding = 0 ) uniform modelUniformBuffer
{
    layout(offset = 0) mat4 u_modelMatrix;
    layout(offset = 64) mat4 u_modelInverseMatrix;
};
layout( std140, binding = 1 ) uniform viewProjectionUniformBuffer
{
    layout(offset = 0) mat4 u_viewMatrix;
    layout(offset = 64) mat4 u_viewInverseMatrix;
    layout(offset = 128) mat4 u_projectionMatrix;
    layout(offset = 192) mat4 u_projectionInverseMatrix;
};
layout( location = 1 ) in vec3 a_normal ;
layout( location = 1 ) out vec3 v_normal ;
layout( location = 0 ) in vec3 a_position ;
layout( location = 0 ) out vec3 v_position ;
layout( location = 2 ) in vec2 a_texcoord0 ;
layout( location = 2 ) out vec2 v_texcoord0 ;
void main (void) {
    vec4 pos = u_viewMatrix * u_modelMatrix * vec4 ( a_position, 1.0 ) ;
    v_normal = transpose( mat3( u_viewInverseMatrix ) ) * transpose(
mat3( u_modelInverseMatrix ) ) * a_normal;
    v_texcoord0 =a_texcoord0 ;
    gl_Position =u_projectionMatrix * pos ;
}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2099>,
or mute the thread

**Comment by linuxaged** [comment]
@chrisforbes , fixed, thanks!
