### ISSUE TITLE
text relocations in 32-bit loader build on Linux

### ISSUE THREAD

**Issue by airlied** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2111]
Since the asm changes went in for the unknown device extensions, we've been seeing TEXTRELs in the vulkan loader library on 32-bit x86 systems. TEXTRELs anger the security people.

I've looked at the code, and I think something like the below should work, but I'm not export on relocations.

diff --git a/loader/unknown_ext_chain_gas.asm b/loader/unknown_ext_chain_gas.asm
index 798760b..0e9be89 100644
--- a/loader/unknown_ext_chain_gas.asm
+++ b/loader/unknown_ext_chain_gas.asm
@@ -89,7 +89,7 @@ vkPhysDevExtTermin\num:
 terminError\num:
     mov     eax, [eax + INSTANCE_OFFSET_ICD_TERM]                               # Load the loader_instance into eax
     push    [eax + (HASH_OFFSET_INSTANCE + (HASH_SIZE * \num) + FUNC_NAME_OFFSET_HASH)] # Push the func name (fifth arg)
-    push    offset termin_error_string                                          # Push the error string (fourth arg)
+    push    offset termin_error_string@GOT                                 # Push the error string (fourth arg)
     push    0                                                                   # Push zero (third arg)
     push    VK_DEBUG_REPORT_ERROR_BIT_EXT                                       # Push the error logging bit (second arg)
     push    eax                                                                 # Push the loader_instance (first arg)

**Comment by airlied** [comment]
also possible this should be @GOTOFF

**Comment by lenny-lunarg** [comment]
When I run `scanelf` on the 32-bit loader as it is currently in master, I get an error on the loader. When I make your suggested change, the error goes away. When I test it, it seems good. On top of that, we're already using `@GOTPCREL` for the 64-bit loader. I believe that I added `@GOTPCREL` to the 64-bit code to solve this exact issue, but I didn't add it to the 32-bit code because it won't assemble, and I wasn't aware that I could use `@GOT` in its place.

I just pushed this fix to master with commit 560f9cdf78d3d03dbf97be638becd1a7df5fa154. I believe this should resolve your issue. If it doesn't, let me know and I can reopen the issue.
