### ISSUE TITLE
Vsync in cube demo malfunctions in high-contrast mode

### ISSUE THREAD

**Issue by AdaDoom3** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2124]
The cube demo behaves strange when the windowing theme is changed to high-contrast mode in Windows 8.1

![image of failure](https://i.stack.imgur.com/iEEUp.gif)

**Comment by AdaDoom3** [comment]
More details here:
https://stackoverflow.com/questions/46632785/vulkan-fails-to-present-on-some-platforms

**Comment by DominikWitczakAMD** [comment]
This sounds like a driver-side issue to me ..

**Comment by AdaDoom3** [comment]
Bingo...

If anyone in a position to fix this needs help (e.g. for verification or more info) I am keeping a close eye on this issue and respond promptly.

**Comment by DominikWitczakAMD** [comment]
So what's your config, exactly?

**Comment by AdaDoom3** [comment]
Alienware 13 Laptop
BIOS: 1.2.2
OS: Windows 8.1 Build 9600
Driver: Vanilla 387.92 install (tried with many drivers though including Vulkan BETA)
GPU: GeForce GTX 960M

https://pastebin.com/A9L5nwth

**Comment by jeremyk-lunarg** [comment]
We tried this on a Windows 8.1 desktop and a Windows 10 desktop, both with Nvidia GTX 750 graphics cards and were unable to reproduce the problem.  However, when testing on a Windows 10 laptop, there are significant issues when running with the Intel driver in high-contrast mode, and as the Optimus layer is involved on laptops the Intel driver might be involved.  Since this does not seem to be a Vulkan-LoaderAndValidationLayers issue we are closing for now, but should  you find a more reproducible example or one that manifests on a desktop machine, please reopen the issue.

**Comment by AdaDoom3** [comment]
Yes, this is related to laptops as the link to the stack overflow post under this ticket describes. As you are probably familiar Optimus is impossible to completely disable on a lot of modern laptops which is unfortunate considering how my current Vulkan binding as well as the cube demo malfunction so dramatically and yet still pass all validation and renderdoc inspection.

Have you filed an issue with Intel and or Nvidia? @jeremyk-lunarg @DominikWitczakAMD

**Comment by DominikWitczakAMD** [comment]
No.

**Comment by AdaDoom3** [comment]
Ok, Thanks for the help. @DominikWitczakAMD @jeremyk-lunarg
