### ISSUE TITLE
Barrier validation: clarify acceptable access masks for TOP_OF_PIPE etc

### ISSUE THREAD

**Issue by chrisforbes** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2172]
CTS tries to issue a barrier with (TOP_OF_PIPE, SHADER_READ_BIT) in a bunch of cases. Is this valid?

**Comment by jozefkucia** [comment]
I haven't looked at the mentioned CTS tests, but TOP_OF_PIPE is useful for layout transition and queue ownership operations. The Vulkan spec states the following:

> Similarly an execution dependency with only VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT
> in the source stage mask will effectively not wait for any prior commands to complete.
> 
> When defining a memory dependency, using only VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT or VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT would never make any accesses available and/or visible because these stages do not access memory.
> 
> VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT and VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT are useful for accomplishing layout transitions and queue ownership operations when the required execution dependency is satisfied by other means - for example, semaphore operations between queues.

**Comment by chrisforbes** [comment]
Spec says:

```
An application must not specify an access flag in a synchronization command if it does not include a pipeline stage in the corresponding stage mask that is able to perform accesses of that type.```

So I think this is invalid. The easiest fix where the CTS tests don't know what stage is going to use the resource next may be to just swap TOP_OF_PIPE_BIT here for ALL_GRAPHICS (or, where it may be compute, ALL_COMMANDS) ?

**Comment by jozefkucia** [comment]
Right, this is invalid. Yes, I think that ALL_COMMANDS should work fine.

I've looked a bit one some CTS tests with TOP_OF_PIPE, and I think that in some cases barriers are redundant. Barriers with the first synchronization scope (TOP_OF_PIPE, HOST_WRITE_BIT) generally should not be needed because submitting a batch of command buffers defines a memory dependency:

> When batches of command buffers are submitted to a queue via vkQueueSubmit, it defines a
memory dependency with prior host operations, and execution of command buffers submitted to
the queue.

>The first access scope includes all host writes to mappable device memory that are either coherent,
or have been flushed with vkFlushMappedMemoryRanges.
The second access scope includes all memory access performed by the device.

**Comment by chrisforbes** [comment]
@jozefkucia sounds plausible.

Filed https://gitlab.khronos.org/Tracker/vk-gl-cts/issues/806 for the first class of these; more to follow

**Comment by krOoze** [comment]
It seem to have been refined in the spec in Table 4. Supported access types.
None of the flags list `TOP_OF_PIPE` and no other stages are implicitly added since it is `srcStage`.
`VK_ACCESS_MEMORY_READ_BIT` and `VK_ACCESS_MEMORY_WRITE_BIT` would be a grey area though because they list "N\A" in the table (whatever that means).
