### ISSUE TITLE
Building with clang/libc++ is broken

### ISSUE THREAD

**Issue by elkrejzi** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2303]
When building Vulkan-LoaderAndValidationLayers from latest git master, the build fails with [1].

The problem happens because #include <string> is missing in the generated file. Adding "#include <string>" to the generated icd/mock_icd.h file fixes the issue. The question remains where the include should really go.

[1] https://gist.github.com/elkrejzi/257bdadaebd82c74b1f1caaa59f2b616

**Comment by karl-lunarg** [comment]
This build is passing on [CI](https://travis-ci.org/KhronosGroup/Vulkan-LoaderAndValidationLayers/builds).

Also, my generated `mock_icd.h` file, starting at line 25, looks like this:

```c++
#include <unordered_map>
#include <mutex>
#include <cstring>
#include "vulkan/vk_icd.h"
namespace vkmock {
```

It is likely that we'll need more information about your platform/environment in order to diagnose any further.
It may be useful for you to post the generated files.

**Comment by elkrejzi** [comment]
Sorry, I forgot to mention. The build fails when clang++ uses libc++ as its standard library. My clang is built so libc++ is the default lib, and you can change the behaviour using -stdlib=libc++ otherwise (you need to install libc++ first).

**Comment by karl-lunarg** [comment]
@elkrejzi   Instead of
```c
#include 
```
Did you really mean:
```c
#include <string>
```

If so, that seems to fix it.  I'll submit a PR.

**Comment by elkrejzi** [comment]
@karl-lunarg Yes, that's what I meant, github stripped the string part (with brackets).
