### ISSUE TITLE
Layers require VK_KHR_get_physical_device_properties2 to call vkCmdPushDescriptorSetKHR

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2363]
When creating a device with `VK_KHR_push_descriptor` extension and trying to call `vkCmdPushDescriptorSetKHR`, validation layers issue the following error:

> [ParameterValidation] Attemped to call vkCmdPushDescriptorSetKHR() but its required extension VK_KHR_get_physical_device_properties2 has not been enabled

Now, the spec does say that `VK_KHR_push_descriptor` requires `VK_KHR_get_physical_device_properties2` but I'm not 100% sure what that means. It seems to me that the current behavior is non-intuitive and slightly odd - the only reason I would need `VK_KHR_get_physical_device_properties2` for `vkCmdPushDescriptorSetKHR` is to check the descriptor count limits, but the spec guarantees a minimum of 32 available descriptors so I can easily write conformant programs without doing that.

**Comment by krOoze** [comment]
This is a specification Issue. As you noted the layers do exactly what the spec says.

`VK_KHR_push_descriptor` needs `VK_KHR_get_physical_device_properties2` because it extends `VkPhysicalDeviceProperties` (and the core version was not extensible).

Theoretically it could work the way you want (and you could make an Issue at the [Specification repo](https://github.com/KhronosGroup/Vulkan-Docs/issues)), but I don't think it is practical:

1) `VK_KHR_get_physical_device_properties2` is one of those extansions (like `maintenance`) that more of a **fixes** things that was omitted in 1.0 than actually "extends". In that light any future extensions could be forgiven for depending on those extensions.

2) The only downside is that the user has to add `VK_KHR_get_physical_device_properties2` extension even if he does not "use" it.

3) I think the layers gave up some times ago and themselves use `vkGetPhysicalDeviceProperties` to get the limits for simplicity (without worrying about minimums or waiting for the user to call `vkGetPhysicalDeviceProperties`). Your suggestion would require some special handling.

**Comment by zeux** [comment]
I'm not sure I understand p.3 - I don't see layers calling vkGetPhysicalDeviceProperties2KHR anywhere (or validating maxPushDescriptors - I guess they will need to start doing it at some point...).

One other peculiar point is that layers emit this error when trying to call vkCmdPushDescriptorSetKHR, *not* when trying to create the device with VK_KHR_push_descriptors. Is it even valid to create a device without specifying dependent extensions?..

I agree that the issue isn't that severe of course - it's a papercut.

**Comment by krOoze** [comment]
>  I don't see layers calling vkGetPhysicalDeviceProperties2KHR 

Look e.g. here: https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/323def7161ff186a3a6df5fb712a85d74323ae7b/layers/parameter_validation_utils.cpp#L467

> One other peculiar point is that layers emit this error when trying to call vkCmdPushDescriptorSetKHR, not when trying to create the device with VK_KHR_push_descriptors.

Certainly, this should be checked/reported on `vkCreateDevice`.
It seems to be autogenerated, so probably a problem for all extension commands with dependencies...

> Is it even valid to create a device without specifying dependent extensions?

No. It is undefined behavior. It has accompanying VU in the latest specification.

> I agree that the issue isn't that severe of course - it's a papercut.

Those suck. They heal for like over a week 😉

**Comment by zeux** [comment]
I've opened #2366 to perform extension check earlier; it's unfortunate that the dependent extension is necessary in this case but so be it.
