### ISSUE TITLE
Presence of ICD json causes loader errors when loading layers

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2403]
I'm seeing some peculiar behavior that I believe may be a bug in the loader.
This is all on a Linux system.
First build the LVL repo to "<lvl_dir>/dbuild" and set "VK_LAYER_PATH=<lvl_dir>/dbuild/layers".
Then, from <lvl_dir>/dbuild/demos run "**./cube --validate**"

This works fine although I currently get an error about "Failed to open JSON file VkLayer_device_simulation.json" that is irrelevant for this issue.

Now, copy the mock ICD json file to the "<lvl_dir>/dbuild/layers" dir and re-run cube:
**cp <lvl_build>/dbuild/icd/VkICD_mock_icd.json <lvl_build>/dbuild/layers/.**
**./cube --validate**

Now I get a message that the mock ICD json is ignored, but it's followed by some additional messages about failing to find threading & object_tracker layers:

> WARNING: [loader] Code 0 : loader_add_layer_properties: Can not find 'layer' object in manifest JSON file /usr/local/google/home/tobine/vulkan_public/Vulkan-LoaderAndValidationLayers/dbuild/layers/VkICD_mock_icd.json.  Skipping this file.
> WARNING: [loader] Code 0 : loader_add_meta_layer: Failed to find layer name (null) component layer VK_LAYER_GOOGLE_threading to activate
> WARNING: [loader] Code 0 : loader_add_meta_layer: Failed to find layer name (null) component layer VK_LAYER_LUNARG_object_tracker to activate
> WARNING: [loader] Code 0 : loader_add_meta_layer: Failed to find layer name (null) component layer VK_LAYER_GOOGLE_threading to activate
> WARNING: [loader] Code 0 : loader_add_meta_layer: Failed to find layer name (null) component layer VK_LAYER_LUNARG_object_tracker to activate

What's up with the additional warnings? Why are they repeated twice? I feel like the presence of the mock ICD json file in the layers dir is potentially exposing a bug in the loader. @lenny-lunarg PTAL.

**Comment by karl-lunarg** [comment]
I found a similar issue yesterday and told Lenny about it.  I was going to file an issue today.  In my case, I had the ICD JSON in the same directory as the layer JSONs and set VK_LAYER_PATH to that directory.  This is probably the same as Tobin's setup, except that the ICD JSON pointed to the ICD binary correctly and was not ignored.  I was running vulkaninfo.  In this config, vulkaninfo reported no explicit layers available.  But if I moved the ICD JSON out, vulkaninfo reported the layers as expected.

Questions for @tobine:

> This works fine although I currently get an error about "Failed to open JSON file VkLayer_device_simulation.json" that is irrelevant for this issue.

Was this caused by you having this layer listed in VK_INSTANCE_LAYERS?  Otherwise, I don't see how you would have seen this.  I know this may not be relevant, but would be useful to understand.

>Now I get a message that the mock ICD json is ignored,

Copying the ICD binary or fixing the `library_path` in the JSON would probably have fixed this.  Again, perhaps not relevant, but still useful to confirm.

I think that the messages come out twice because there is some intentional logic in the loader that causes it to discover the ICDs and layers more than once.  I don't recall the reasons ATM.

But yes, there seems to be a definite problem when the ICD JSONs are in the same place as the layer JSONs.

**Comment by tobine** [comment]
@karl-lunarg Looking at my workspace I see that the device_simulation message was due to a dead link I had created manually. When I kill that link the message goes away and I did a clean build to confirm that the link is not there normally. I'm sure this is from a while back when I was testing devsim w/ mock ICD.

I placed the mock ICD "libVkICD_mock_icd.so" file into the layers dir and I see the same warning messages as I originally reported. Note that I was not attempting to use the mock ICD, just using desktop driver and noticed that presence of mock ICD json file caused different behavior.
