### ISSUE TITLE
Missing validation: VkWriteDescriptorSet.dstSet != VK_NULL_HANDLE

### ISSUE THREAD

**Issue by hrydgard** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2556]
When not using push descriptors, setting this field when using vkUpdateDescriptorSets is of course mandatory. Found this one while backporting from push descriptors to normal descriptor usage.

Though, of course, it should be allowed to be null when used in vkCmdPushDescriptorSetKHR.

**Comment by tobine** [comment]
This is VALIDATION_ERROR_15c00280. The Issue appears to be [here](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/object_tracker_utils.cpp#L210) in object_tracker. We only check for the error case when dstSet is not NULL.
@mark-lunarg can you give this to someone?

**Comment by mark-lunarg** [comment]
ICYMI, @jzulauf-lunarg is an actual Hero. 🥇

**Comment by jzulauf-lunarg** [comment]
Very curious, [parameter_validation](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/parameter_validation_utils.cpp#L2079)  already has this check (since [Aug 17](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/34655dd548a9b171bcee33508932bcc0b46fff11) at least), as I discovered when (in testing for the fix to object_tracker) I add a unit test with a VK_NULL_HANDLE dstSet.  I got the expected error message for my fix, but also received an 'Unexpected' message from parameter_validation.

> Unexpected: Object: VK_NULL_HANDLE (Type = 0) | vkUpdateDescriptorSets: required parameter pDescriptorWrites[0].dstSet specified as VK_NULL_HANDLE

I can remove the one from parameter validation, or leave object tracker as it is and add the VUID information from parameter validation. Preferences @mark-lunarg , @tobine ?

@hrydgard  -- what call using VkWriteDescriptorSet were you using and which validation layers were enabled when you tested?

From what I'm looking at the null check in object_tracker is similar to what is done for srcSet/dstSet in VkCopyDescriptorSet, where the null check is in the parameter_validation layer, and !null validation checks are done in the object_tracker.

**Comment by hrydgard** [comment]
I run with "VK_LAYER_LUNARG_standard_validation". But I just now realized that I just reinstalled this particular machine and forgot to install the Vulkan SDK :(  I had debugged on another machine earlier which did have working validation so I didn't realize.  Trying with the latest now it does actually catch it. Sorry :(
