### ISSUE TITLE
vkEnumerateInstanceExtensionProperties crashes in Nvidia driver when LunarG SDK installed

### ISSUE THREAD

**Issue by httpdigest** [KhronosGroup/Vulkan-LoaderAndValidationLayers#302]
Since I installed the 1.0.5.0 version of the LunarG SDK with the validation layers I am experiencing a bug which makes calling vkEnumerateInstanceExtensionProperties() with a non-null pProperties crash in Nvidia's nvoglv64.dll driver DLL. The error in the 1.0.5.0 SDK occurred only in around 1 out of 10 runs of the program.
Now that I installed the 1.0.8.0 SDK, the error occurs almost always, so now it just does _not_ occur in 1 out of 10 runs.
The symptoms are that either nvoglv64.dll hangs somewhere within the vkEnumerateInstanceExtensionProperties() (checked with attaching a native platform debugger, suspending the threads and seeing where they resided) or - what happens most of the time - that it crashes the process with an access violation.
The issue is very undeterministic and only happens when the LunarG SDK is installed. I have tried about 100 runs of 20 different Vulkan programs which all ran fine when the LunarG SDK was uninstalled.
There seems to be some really nasty concurrency problem there, I guess. Also, the issue does not exist when running the native program under a native platform debugger from the start and stepping through the code instruction by instruction to find the offending one.
I checked that it was indeed vkEnumerateInstanceExtensionProperties() crashing by having fprintf/fflush before and after each Vulkan function call.

The very first Vulkan functions being called that lead to the crash described are:
- vkEnumerateInstanceExtensionProperties(NULL, &count, NULL)
- vkEnumerateInstanceExtensionProperties(NULL, &count, ep)

The second call crashes. No other Vulkan calls were being made before. Just LoadLibrary("vulkan-1.dll") and GetProcAddress("vkGetInstanceProcAddr")

System specifications:
- OS: Windows 7 x64 SP1 (all recent updates installed)
- GPU: Nvidia Quadro K2000M
- Driver: Nvidia 364.72 WHQL
- LunarG SDK: 1.0.8.0

This issue also makes any GLFW application not working, because they call vkEnumerateInstanceExtensionProperties to detect the instance extensions like VK_KHR_win32_surface and VK_KHR_surface to know whether Vulkan is enabled.

**Comment by pdaniell-nv** [comment]
Any chance the memory pointed to by "ep" is not large enough? How is it allocated?

**Comment by httpdigest** [comment]
Sadly no. I am exactly using GLFW from its current head.
See: https://github.com/glfw/glfw/blob/master/src/vulkan.c#L81

**Comment by pdaniell-nv** [comment]
I wasn't able to reproduce this locally with SDK 1.0.8.0 installed and the "examples" that glfw builds like "wave" and "particles". Are there any extra repro steps I should know about.

Since you mention it's related to the SDK, can you try uninstalled all SDKs and Vulkan Run Time Libraries from the system and reinstall 1.0.8.0 and the runtime library. After doing the uninstall, make sure that HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ExplicitLayers and HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers are empty and also there are no VulkanSDK or VulkanRT entries in HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall. If there are, you'll need to rerun the "UninstallString" for each entry until their "InstallCount" goes to 0 and the entry disappears.

Perhaps there is some layer that is modifying the parameters so that when they finally get to the driver there is something wrong with them.

**Comment by httpdigest** [comment]
Thanks for taking care of it!
I have created the following simple C demo to reproduce. The error happens about 95% of the program run in non-debug mode:
```C
#include <Windows.h>
#include <stdio.h>
#include "vulkan.h"
int main(int argc, char** argv) {
	HMODULE mod = LoadLibraryA("vulkan-1.dll");
	PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr = (PFN_vkGetInstanceProcAddr) GetProcAddress(mod, "vkGetInstanceProcAddr");
	PFN_vkEnumerateInstanceExtensionProperties vkEnumerateInstanceExtensionProperties = (PFN_vkEnumerateInstanceExtensionProperties) vkGetInstanceProcAddr(NULL, "vkEnumerateInstanceExtensionProperties");
	uint32_t count;
	VkResult result = vkEnumerateInstanceExtensionProperties(NULL, &count, NULL);
	VkExtensionProperties* props;
	props = (VkExtensionProperties*) calloc(count, sizeof(VkExtensionProperties));
	fprintf(stderr, "%s\n", "Before..."); fflush(stderr);
	result = vkEnumerateInstanceExtensionProperties(NULL, &count, props); // <- crashes right here!
	fprintf(stderr, "%s\n", "After..."); fflush(stderr);
	return 0;
}
```

**Comment by httpdigest** [comment]
Okay, I uninstalled the Vulkan SDK 1.0.8.0 and also the Vulkan Runtime Library 1.0.8.0 and Vulkan Runtiem Library 1.0.5.3, which were present as installed programs.
But now that also uninstalled the vulkan-1.dll. So I cannot run any Vulkan programs anymore.
Aren't the graphics card drivers supposed to provide that dll?

**Comment by httpdigest** [comment]
I just uninstalled everything. All Vulkan Runtime Libraries and the SDK and also the graphics driver and reinstalled only the graphics driver. That fixed vulkan-1.dll being around again.
Now, all Vulkan apps work just fine (that is without having the SDK installed).
I will now reinstall the SDK.

**Comment by httpdigest** [comment]
Thanks again! After manually deleting the registry keys and reinstalling the 1.0.8.0 SDK, everything seems to work fine now. Also actually enabling layers works now.
Sadly I did not remember what the 11 values in the HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ExplicitLayers and the 1 value in HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers contained exactly.
Now, HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ExplicitLayers contains 11 values such as "C:\VulkanSDK\1.0.8.0\Bin\VkLayer_image.json".
For me, this issue is now solved.

**Comment by pdaniell-nv** [comment]
Awesome, I'm glad the issue has been resolved. There may be a bug with the SDK uninstall or overinstall not removing old incompatible layers. If you see it again see if you can file an issue against the Vulkan-LoaderAndTools repo.

**Comment by romanlarionov** [comment]
@pdaniell-nv @httpdigest 

Sorry for reopening an old thread, but I seem to be having the same issue. 
Excuse me if I sound like a doob, but I'm not entirely sure what HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ExplicitLayers and HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers refer to. Are they file paths? Because I can't `cd` to it. 

Thanks.

**Comment by MarkY-LunarG** [comment]
@romanlarionov, those paths are referring to locations in the Windows Registry.  If you open RegEdit, you should be able to find them. If you're having a similar problem, you should try running the VIA application that comes in the new LunarG SDK and it will likely give you much of the information you're interested in since it extracts this information for you.

**Comment by romanlarionov** [comment]
Thanks for the help @MarkMLunarG. Sorry for the late response. Finals took priority. 

I tried what you suggested but I had an issue with the new 1.0.33 LunarG SDK. It only worked after I installed the SDK with administrative privileges. 

You can see an ongoing log on this issue: https://vulkan.lunarg.com/issue/view/584544cb9ab0fa4b673614b2
