### ISSUE TITLE
getInstanceProcAddr WSI extensions requires loader support

### ISSUE THREAD

**Issue by ystreet** [KhronosGroup/Vulkan-LoaderAndValidationLayers#305]
What I'm seeing is that getInstanceProcAddr()-ing a WSI extension requires the loader to support that WSI interface.  If the driver supports that extension but the loader does not, then when the application calls the returned function, the driver will receive the application's VkInstance instead of the ICD VkInstance held by the loader.

e.g. the intel vulkan driver exposes the wayland WSI extension that the loader by default does not.  Building the loader with wayland support will of course avoid this issue.

Reproducible with https://github.com/krh/vkcube/pull/9 and/or https://cgit.freedesktop.org/gstreamer/gst-plugins-bad/commit/?id=65770c2af944ba2b222c74bd08dd8a1d01431149

**Comment by jon-lunarg** [comment]
Right now for WSI Linux extensions, the CMake file defaults to only Xcb is enabled, not Wayland, Xlib, or Mir.    There are several considerations of why this is for now.  Yes the loader needs to be compiled with Wayland support enabled.

Does  the EnumerateInstanceExtensionProperties() return the VK_KHR_wayland_surface extension even if the loader is built without Wayland enabled? If so that would be a bug.  If not then  I think the app  should not be calling GetInstanceProcAddr with a VK_KHR_Wayland_surface entry point unless
it successfully enumerates and enables the extension.

**Comment by ystreet** [comment]
Right, 1.0.5 of the loader exposed the wayland surface extension without having support for it.  1.0.8 doesn't and things fail as expected.

**Comment by jon-lunarg** [comment]
So is there a bug here? I think we are saying SDK 1.0.8 behaves as expected (Given that it was built with Wayland, Xlib and Mir surface extensions disabled).

**Comment by ystreet** [comment]
Not that I can see anymore.
