### ISSUE TITLE
Validate memory allocation size in device_limits

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#373]
Moved from gitlab 117

When binding memory to an image or buffer the size of the memory must be of at least size specified with getimage/buffer memory requirements. Additionally, the returned memory type bits must be adhered to. This can be validated by querying this information when the physical device is created within mem tracker and then checking it at bind time with the properties of the allocation stored at alloc time.

Norbert Nopper @FslNopper  2 months ago
Also, do bounds checking in the mem tracker when uploading data to the memory.

**Comment by tobine** [comment]
Assigning to @cdwfs as a good follow-on to his recent work. In a quick check I don't believe that we've validating this yet. This should be done for both buffers and images. We do make sure that that <img/buff_state_ptr>->requirements has the requirements, and we check alignments, but not size or memoryTypeBits that I can see.

Also in a quick check of the code I see that Insert[Buffer|Image]MemoryRange() is being called from the PreCallValidate* functions and updating the state. This should be re-factored so that the state update only occurs if validation passes.

**Comment by cdwfs** [comment]
Thanks, I'll get right on it while the Bind*Memory() code is fresh in my head. Could you point me towards the relevant VU codes that still need to be checked/reported/tested? If I'm not mistaken, it should just be the size-related ones; the memory type bits were already being checked (see the ValidateMemoryTypes() function). I added a test for this in my last PR (VU 797, 806).

**Comment by tobine** [comment]
Errors VALIDATION_ERROR_00797 & VALIDATION_ERROR_00806 related to memoryTypeBits say they're already implemented with tests in BindInvalidMemory so shouldn't need to do anything there after all.
VALIDATION_ERROR_02175 is for size limit on vkBindBufferMemory() and still needs to be done.
VALIDATION_ERROR_02179 is the equivalent check for Images.

**Comment by cdwfs** [comment]
Fixed with #1495
