### ISSUE TITLE
debug report tries to read from possibly stack allocated memory

### ISSUE THREAD

**Issue by heeen** [KhronosGroup/Vulkan-LoaderAndValidationLayers#415]
in cube.c, VkPipelineColorBlendAttachmentState att_state[1] is allocated on the stack.
The debug report will try to read from it later, from vkCmdDraw, reporting bogus values.

**Comment by tobine** [comment]
Yes, this is a bug due to the fact that safe_struct generator treats 'VkPipelineColorBlendStateCreateInfo' as an exception which then prevents a deep copy of the attachments. Correct fix is to update safe_struct generator to handle static arrays such as the "blendConstants[4]" in "VkPipelineColorBlendStateCreateInfo".
I'll get around to this eventually but low priority at the moment.

**Comment by tobine** [comment]
Submitted #580 to fix this issue

**Comment by tobine** [comment]
Fix was pushed to master
