### ISSUE TITLE
VulkanRT uninstaller flagged by AV containing trojan

### ISSUE THREAD

**Issue by bruceepper** [KhronosGroup/Vulkan-LoaderAndValidationLayers#474]
A driver update on my system apparently installed VulkanRT v 1.0.8.1. Norton Security immediately flagged (and blocked it from being written to the disk) the uninstaller (UninstallVulkanRT.exe) from the system since it contains a generic Trojan.

Filename: uninstallvulkanrt.exe
Threat name: Trojan.GenFull Path: c:\program files (x86)\vulkanrt\1.0.8.1\uninstallvulkanrt.exe

____________________________

____________________________

On computers as of 
5/3/2016 at 5:52:01 AM

Last Used 
5/3/2016 at 5:52:01 AM

Startup Item 
No

Launched 
No

Threat type: Virus. Programs that infect other programs, files, or areas of a computer by inserting themselves or attaching themselves to that medium.

____________________________

uninstallvulkanrt.exe Threat name: Trojan.Gen
Locate

Few Users
Fewer than 50 users in the Norton Community have used this file.

Very New
This file was released less than 1 week  ago.

High
This file risk is high.

____________________________

Source: External Media

____________________________

File Actions

File: c:\program files (x86)\vulkanrt\1.0.8.1\ uninstallvulkanrt.exe Blocked
____________________________

File Thumbprint - SHA:
Not available
File Thumbprint - MD5:
Not available

**Comment by MarkY-LunarG** [comment]
We received a few reports that some virus scanners are reporting a possible Trojan found in the uninstallVulkanRT.exe file that is a part of the Vulkan SDK and Runtime installs.  Specifically, it was reported for SDK or Runtime versions 1.0.8.0, 1.0.8.1, and 1.0.11.0.

Our analysis to date suggests that these reports are false positives.  It appears likely that the virus scanners are finding a pattern match in the binary data of that file and has been flagged as a possible Trojan being present.

To aid in our investigation, we've been using VirusTotal [https://www.virustotal.com/].

When uploading the suspect file from 1.0.8.0, 1.0.8.1, and 1.0.11.0, 9 / 56 reported seeing a Trojan or other issue.  These were:
 - Ad-Aware	Gen:Trojan.Heur.FU.uy3@aCmIq6hi
 - Arcabit	Trojan.Heur.FU.E18E03
 - BitDefender	Gen:Trojan.Heur.FU.uy3@aCmIq6hi
 - Emsisoft	Gen:Trojan.Heur.FU.uy3@aCmIq6hi
 - F-Secure	Gen:Trojan.Heur.FU.uy3@aCmIq6hi
 - GData	Gen:Trojan.Heur.FU.uy3@aCmIq6hi
 - eScan	Gen:Trojan.Heur.FU.uy3@aCmIq6hi
 - Qihoo-360	HEUR/QVM20.1.0000.Malware.Gen
 - Symantec	Suspicious.Cloud.9

Some of the scanners that did not report an issue include:
 - AVG
 - AVware
 - Avast
 - Baidu
 - DrWeb
 - Kapersky
 - Kingsoft
 - Malwarebytes
 - McAfee
 - McAfee-GW_Edition
 - Microsoft

We investigated but didn't observe any of the reported virus behaviors such as a specific EXE file being placed in the %TEMP% folder or the registry being updated. 

As part of fixing an unrelated issue, we rebuilt NSIS and some of the components used by NSIS to form our installer/uninstaller.  We believe that this recompilation (using only different compiler options) rearranged the generated code sufficiently so that all but one of the virus scanners no longer detect the misleading virus signature.   The remaining complaint was reported by Qihoo which already has a large list of false positives listed on their web-site.

We have submitted a copy of the original uninstallVulkanRT.exe file to BitDefender requesting analysis of a possible false positive.

To remove what we believe are false positives, we are planning to build a new SDK and Runtime, 1.0.11.1, using the recompiled NSIS tools.  We plan to deliver this new SDK and Runtime in the next day or two. 

We sincerely apologize for any inconvenience.

**Comment by MarkY-LunarG** [comment]
1.0.11.1 SDK is out and should have the changes necessary to stop Virus scanner warnings.

**Comment by MarkY-LunarG** [comment]
We heard back from BitDefender. They verified this was a false positive and a future version will no longer claim a Trojan is present. In the meantime, we have also released the modified file in the 1.0.11.1 SDK which will no longer show the issue as well.

**Comment by spectruminfinitum** [comment]
what's wrong with nvidia or vulkan? some bot net on the recipe??
\VulkanRT-Installer.exe: Win.Trojan.Agent-1426210 FOUND

**Comment by lenny-lunarg** [comment]
Spectrum, what version of the Vulkan runtime do you have and which Nvidia driver are you running?

**Comment by spectruminfinitum** [comment]
1.0.11.1

**Comment by germulvey** [comment]
Clamav also detecting this as trojan infection

clamscan --recursive=yes --infected /win7
/win7/Program Files (x86)/qBittorrent/uninst.exe: Win.Adware.Opencandy-31 FOUND
/win7/Users/Gerard/AppData/Local/Temp/VulkanRT/vcredist_x64.exe: Win.Trojan.Agent-1426210 FOUND
/win7/NVIDIA/DisplayDriver/368.81/Win8_WinVista_Win7_64/International/Display.Driver/VulkanRT-Installer.exe: Win.Trojan.Agent-1426210 FOUND
/win7/Program Files/NVIDIA Corporation/Installer2/Display.Driver.{394080F6-2C6D-43EF-8D0A-7D9CA251E9AC}/VulkanRT-Installer.exe: Win.Trojan.Agent-1426210 FOUND

**Comment by lenny-lunarg** [comment]
So, these antiviruses have been occasionally triggering on our installers and uninstallers for a while. Unfortunately, its not easy to get all of them to stop because there's a ton of different antiviruses and because the antivirus vendors have a strong tendency to ignore people who submit false positives to them. Furthermore, the virus definitions change frequently, so it's not uncommon for our software to either be suddenly marked as a virus, or suddenly no longer be marked as a virus, with the file itself not having changed in any way. That being said, we do keep track of the antiviruses that flag on our installers, and we generally try to reduce them, or at least update the thread on LunarXChange when there's a significant change. The thread is at:

https://vulkan.lunarg.com/app/issues/576c5b9b2133180eb1606687

You will need to be logged in to LunarXChange for that link to work. The antivirus vendors that we have heard back from have universally agreed that their antiviruses were reporting false positives, and the vast majority of antiviruses (generally about 98%) do not report any issues with out installers, so we're confident that these are false positives.

As to the immediate issue with ClamAV that @germulvey posted, ClamAV reported a virus in the 1.0.11.1 runtime installer (I beleive Nvidia is still using 1.0.11.1, though I'm not positive), but it should not in 1.0.17.0 or later (I can't remember about 1.0.13.0). We're pretty sure that it's safe to ignore the virus warning, but if that bothers you, you can always block that installation and install a newer version manually.

If you do want to install the Vulkan runtime manually, we include the runtime installer in the SDK, so you would have to download and install the latest SDK (from http://vulkan.lunarg.com), find the runtime installer in a directory labeled "RunTimeInstaller" and run that installer. Using a different runtime from the one bundled with your drivers should be fine as long as the one you use is newer, rather than older.
