### ISSUE TITLE
Provide dependencies to 3rd party packages, such as lxml for Windows

### ISSUE THREAD

**Issue by mathiasschott** [KhronosGroup/Vulkan-LoaderAndValidationLayers#51]
I spent a hairy amount of yak-shaving on getting the layers to build on Windows and my conclusion is that there is room for improvement to stream-line the build process on Windows.

Most layers build successfully, but the dependency on the lxml python package has been most vexing, as manifested with this error during the build of VkLayer_param_checker:

Traceback (most recent call last):
  File "C:/VulkanSDK/Github/Git/genvk.py", line 25, in <module>
    from reg import *
  File "C:\VulkanSDK\Github\Git\reg.py", line 25, in <module>
    from lxml import etree
ImportError: No module named 'lxml'

As part of (unrelated) #39, @cnorthrop and @jon-lunarg provided helpful pointers and documented the dependency in BUILD.md and also point to pre-built Windows binaries of said lxml Python package. 

However in the end this did not work since all links on http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml are dead/and/or timing out with all the various browsers I tried.

Next I tried installing lxml via pip and easy_install, which then turned into an egg-hunt for source for development packages libxml2 and libxslt, which I chased down from ftp://xmlsoft.org/libxml2/win32/ 

But ultimately 'xslt-config' is not recognized as an internal or external command,' oversaturated my thirst to learn more about the curious world of any subset of Python XML package management (or lack thereof).

Which leads to my questions:
1. Is there a specific reason why the both the spec and layers depend on lxml lib and not the core Python built-in XML support?
2. If there is a strong and valid reason would it be possible to provide the dependencies (such as pre-built lxml Windows packages ) as part of the Github repository?
3. When would this be resolved either way?

Regardless of fundamental differences between Windows and Linux wrt setting up a build environment I strongly believe that a key Vulkan ecosystem component, such as the loader & layers should reduce external dependencies to the minimum and if that's not feasible, host those that are not installed by default by other dependencies (such as Python, or Cmake) as part of the Git repository.

**Comment by oddhack** [comment]
If someone wants to submit a patch demonstrating how lxml can be replaced with core Python libraries without significantly affecting the entire registry infrastructure, we could look at it. lxml implements functionality which AFAIK is not supported in the core package, and is used in the scripts. Perhaps better install instructions are all that's needed.

**Comment by mathiasschott** [comment]
Yeah, hosting the Windows packages for lxml here might be the easiest solution.

**Comment by jjulianoatnv** [comment]
It's not just the install instructions. I a 3rd party package cannot be obtained, as Mathias seems to have described, then the build process is simply not accessible no matter how well-written the instructions happen to be.

Also, security audits and other analysis of the Vulkan runtime components are required. Not fully specifying the content of a 3rd party package, by hosting it in Khronos' own repo, is contrary to a successful audit.

**Comment by oddhack** [comment]
Python and gmake are just as "3rd party" as lxml itself, by that measure. I don't think we're going to start hosting entire software distributions in our repos for this hypothetical purpose; when do you propose we start doing security audits on everything in our github repos, and who is going to be doing them?

**Comment by jjulianoatnv** [comment]
I am not proposing adding python to a Khronos repo. If the lxml module is considered sufficient "standard" for python, then I agree it need not be added to a Khronos repo.

Is it really standard? Maybe it is. I don't know much about the Python ecosystem. However the URL to it is at someone's .edu web page. The disclaimer at the top of the page reads:

> The files are unofficial (meaning: informal, unrecognized, personal, unsupported, no warranty,
> no liability, provided "as is") and made available for testing and evaluation purposes.

Note that the .edu web page is not timing out now. I was able to download a .whl file.

**Comment by jon-lunarg** [comment]
Here is a more official Python link for downloading. Maybe we need to start using the lxml module available on this  web site?  I haven't tried it yet, nor do I know anything much about Python ecosystem.
https://pypi.python.org/pypi/lxml/

**Comment by oddhack** [comment]
In addition to pypi as @jon-lunarg notes, Linux distributions already package lxml, and Cygwin packages it here:

https://cygwin.com/cgi-bin2/package-grep.cgi?grep=lxml&arch=x86_64

Hopefully pointing to these places and to the project home page at http://lxml.de/ will suffice.

**Comment by mathiasschott** [comment]
That is what I tried after the .edu link failed.

However the installer s, but they failed to install since I didn't have any of the supported Python versions installed. (I have 2.7, 3.4 and now 3.5 installed)

From what I can tell, 

"C:\Python35\Scripts\easy_install.exe lxml  or 
"C:\Python35\Scripts\pip install lxml" do fetch the package from https://pypi.python.org/pypi/lxml/,

but then fail to build:


C:\Python35\Scripts>easy_install lxml
Searching for lxml
Reading https://pypi.python.org/simple/lxml/
Best match: lxml 3.5.0
Downloading https://pypi.python.org/packages/source/l/lxml/lxml-3.5.0.tar.gz#md5=9f0c5f1eb43ff44d5455dab4b4efbe73
Processing lxml-3.5.0.tar.gz
Writing C:\Users\USER\AppData\Local\Temp\easy_install-h8ldacq8\lxml-3.5.0\setup.cfg
Running lxml-3.5.0\setup.py -q bdist_egg --dist-dir C:\Users\USER\AppData\Local\Temp\easy_install-h8ldacq8\lxml-3.5.0\egg-dist-tmp-ns6o8784
Building lxml version 3.5.0.
Building without Cython.
ERROR: b"'xslt-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
** make sure the development packages of libxml2 and libxslt are installed **

Using build configuration of libxslt
cl : Command line warning D9025 : overriding '/W3' with '/w'
lxml.etree.c
src\lxml\includes\etree_defs.h(14): fatal error C1083: Cannot open include file: 'libxml/xmlversion.h': No such file or directory
Compile failed: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\cl.exe' failed with exit status 2
xmlXPathInitzlyz_hi_.c

**Comment by dustin-lunarg** [comment]
The param checker code that is generated from the XML registry doesn't need to be generated on a per-build basis, so one option here is to check the generated code into the repository and add a CMake option to enable/disable per-build code generation.  Most developers should be fine with the param checker code generation disabled.  Developers modifying the code generation scripts can enable the per-build code generation for testing purposes.  

The generated code should only change when vk.xml or one of the code generation scripts changes, so we'd need to update the generated code that was checked into the repository as part of the process of updating the scripts/XML file.  

The threading layer should have a similar dependency on the XML registry, so would require the same treatment.

**Comment by oddhack** [comment]
I think the underlying problem isn't actually Python-specific. Note

    ** make sure the development packages of libxml2 and libxslt are installed **

above. That just defers the problem one step to obtaining appropriate Windows binaries of libxml2 and libxslt, of course (again: they are already prepackaged for Cygwin), but I think it's the real problem here, not lxml. Apparently the pypi binary Windows packages include prebuilt libxml2/libxslt libraries (I think, if I'm reading the lxml.de install page right) and if so, that could be the way to go.

**Comment by mathiasschott** [comment]
https://github.com/LunarG/VulkanTools/blob/master/BUILDVT.md for example does an excellent job at getting the Image Magick dependencies sorted out by reducing it to "Click, click, build" :)

**Comment by dustin-lunarg** [comment]
The lxml dependency has been removed from the LoaderAndValidationLayers build.

**Comment by jjulianoatnv** [comment]
Summarizing ideas here for the record.


Responding to earlier comments from @jon-lunarg 

> Here is a more official Python link for downloading. Maybe we need to start using the lxml module available on this web site? I haven't tried it yet, nor do I know anything much about Python ecosystem.
https://pypi.python.org/pypi/lxml/

and @oddhack 

> In addition to pypi as @jon-lunarg notes, Linux distributions already package lxml, and Cygwin packages it  ... Hopefully pointing to these places and to the project home page at http://lxml.de/ will suffice.

I am working on consuming vk.xml when building drivers and tools that are hosted on a Windows build host. I want to use the python scripts for parsing vk.xml that are found in the Vulkan-Docs repo. Using cygwin python is not viable within my build system due to configuration management issues related to the use of cygwin, the details of which are outside the scope of this github issue.

There is a fundamental issue that the lxml package relies on binary .dll libraries. While pypi does provide binary wheels of the lxml module for python 2.7, the 32-bit binary binary wheel it provides is for an old version of python 3.x, and it provides no binary wheel for 64-bit python 3.x.  The self-described 'unofficial' uci.edu page provides unofficial binary wheels for modern python 3.x, but using those binaries gets into issues of trust that are reasonable to consider when used in a corporate build farm. Building lxml and the libraries upon which it depends is a non-trivial challenge on the Windows platform, and I would not be surprised if this is a major contributing factor to the fact that the official pypi site is not distributing a modern python 3.x binary wheel for lxml. The bottom line is that navigating the use of lxml on a Windows build host is a genuine challenge in the current CPython ecosystem.


To an earlier point I made about security audits:

> fully specifying the content of a 3rd party package

LunarG publishes binary builds of the Vulkan SDK and the Vulkan Runtime. These builds are made using particular versions of libraries and tools. I'm not aware that LunarG publishes the specific versions of each library and tool that is used to build these binaries. Not knowing this info complicates the ability of a security audit to determine if a specific version of the SDK or the Runtime may contain a vulnerability, assuming a hypothetical situation where a security vulnerability is discovered in one of the libraries or tools that contribute to a published binary SDK and Runtime.

For the case of lxml and the libraries that underlie it, I think they are (or were?) used only at build time, and none of their executable code ends up in the published SDK or Runtime. It is unlikely that the lxml version used to build the SDK or Runtime could be exploited to inject malicious code into the SDK or the Runtime. We can all choose to trust LunarG in this regard, and I am not worried about risk from lxml specifically. However as a matter of principle the published Windows Vulkan SDK and Vulkan Runtime need to be monitored for security risk, and knowing information about how they are built contributes to the ability to evaluate that risk. That principle informed my earlier statement on this issue.

**Comment by oddhack** [comment]
@jjulianoatnv perhaps the new Ubuntu subsytem for Windows 10 will help as it rolls out more widely. There's a recently updated lxml bug here:

https://bugs.launchpad.net/lxml/+bug/1326096

that seems to reduce to "project maintainer is too busy with other stuff they actually care about, but if someone else makes the Windows builds work better, he'll incorporate that into the pypi site. That might be the most direct approach to satisfy your particular needs. There are a lot of prebuilt windows binary packages on there already, there just seems to be a slight hole in the AMD64 coverage that needs to be filled in.

**Comment by courtney-g** [comment]
As of Friday (4/8) the dependency on lxml has been removed.
See SHA 0cf28a25
<https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/0cf28a250c117cb1d11426ddc75c0327297e32e7>
for details.

On Sat, Apr 9, 2016 at 7:46 AM, jjulianoatnv <notifications@github.com>
wrote:

> Summarizing ideas here for the record.
>
> Responding to earlier comments from @jon-lunarg
> <https://github.com/jon-lunarg>
>
> Here is a more official Python link for downloading. Maybe we need to
> start using the lxml module available on this web site? I haven't tried it
> yet, nor do I know anything much about Python ecosystem.
> https://pypi.python.org/pypi/lxml/
>
> and @oddhack <https://github.com/oddhack>
>
> In addition to pypi as @jon-lunarg <https://github.com/jon-lunarg> notes,
> Linux distributions already package lxml, and Cygwin packages it ...
> Hopefully pointing to these places and to the project home page at
> http://lxml.de/ will suffice.
>
> I am working on consuming vk.xml when building drivers and tools that are
> hosted on a Windows build host. I want to use the python scripts for
> parsing vk.xml that are found in the Vulkan-Docs repo. Using cygwin python
> is not viable within my build system due to configuration management issues
> related to the use of cygwin, the details of which are outside the scope of
> this github issue.
>
> There is a fundamental issue that the lxml package relies on binary .dll
> libraries. While pypi does provide binary wheels of the lxml module for
> python 2.7, the 32-bit binary binary wheel it provides is for an old
> version of python 3.x, and it provides no binary wheel for 64-bit python
> 3.x. The self-described 'unofficial' uci.edu page provides unofficial
> binary wheels for modern python 3.x, but using those binaries gets into
> issues of trust that are reasonable to consider when used in a corporate
> build farm. Building lxml and the libraries upon which it depends is a
> non-trivial challenge on the Windows platform, and I would not be surprised
> if this is a major contributing factor to the fact that the official pypi
> site is not distributing a modern python 3.x binary wheel for lxml. The
> bottom line is that navigating the use of lxml on a Windows build host is a
> genuine challenge in the current CPython ecosystem.
>
> To an earlier point I made about security audits:
>
> fully specifying the content of a 3rd party package
>
> LunarG publishes binary builds of the Vulkan SDK and the Vulkan Runtime.
> These builds are made using particular versions of libraries and tools. I'm
> not aware that LunarG publishes the specific versions of each library and
> tool that is used to build these binaries. Not knowing this info
> complicates the ability of a security audit to determine if a specific
> version of the SDK or the Runtime may contain a vulnerability, assuming a
> hypothetical situation where a security vulnerability is discovered in one
> of the libraries or tools that contribute to a published binary SDK and
> Runtime.
>
> For the case of lxml and the libraries that underlie it, I think they are
> (or were?) used only at build time, and none of their executable code ends
> up in the published SDK or Runtime. It is unlikely that the lxml version
> used to build the SDK or Runtime could be exploited to inject malicious
> code into the SDK or the Runtime. We can all choose to trust LunarG in this
> regard, and I am not worried about risk from lxml specifically. However as
> a matter of principle the published Windows Vulkan SDK and Vulkan Runtime
> need to be monitored for security risk, and knowing information about how
> they are built contributes to the ability to evaluate that risk. That
> principle informed my earlier statement on this issue.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/51#issuecomment-207792152>
>



-- 
Courtney
