### ISSUE TITLE
Core Validation: Invalid "explicit dep needed" warning is issued at vkCmdBeginRenderPass() call time.

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#527]
Consider the following renderpass configuration:

* Two attachments are used: color & depth
* Three subpasses are defined (let's name these A, B and C)
* Two dependencies are defined: A->B and B->C

Each subpass uses both two attachments.

At vkCmdBeginRenderPass() call time, I'm seeing the following debug call-back:

![image](https://cloud.githubusercontent.com/assets/17761066/15181300/c9b72902-1786-11e6-8601-bcc38ccd850d.png)

![image](https://cloud.githubusercontent.com/assets/17761066/15181382/35e34bd8-1787-11e6-84b3-f93fbacc94ec.png)

For this particular case, we do not agree an explicit dependency is required.

**Comment by lentinem** [comment]
It is not required. Hence the warning. This had come up before and the consensus was to leave it as a warning but we can bring it up again if you feel that this should be removed.

**Comment by DominikWitczakAMD** [comment]
Can you point me to the previous discussions on this subject? In general, I'm finding thie warning misleading. The first impression it gives is that the renderpass the app has just started recording commands for is broken beyond any repair.

I'm curious as to what language exactly laid ground for this warning.

**Comment by lentinem** [comment]
The discussion happened in a meeting due to a different report of the same issue but it wasn't recorded.

I don't think there was any language that led to this as there generally aren't for warnings. Warnings are generally statements of the form "Check to make sure you mean this." which in this case is check to make sure you mean to have a dependency between these passes.

I'm happy to bring this up again though as I'm not convinced it makes sense to have this; I was on the fence last time it came up.

**Comment by DominikWitczakAMD** [comment]
Admittedly, I have not analyzed the code which brings up the warning in question, but I really believe that the warning should not be issued for straightforward dependency chains like the one I described above.

In order to be able to say more about the threshold where the warning would start making sense for us, I would need to understand more about the reasons, for which this debug callback has been introduced in the first place. Right now, the impression I'm getting is that this warning only decreases the SNR of the validation layers.

I was hoping I would be pointed to some spec language, but if there's none, then I'm a bit baffled as to how to proceed ..

**Comment by lentinem** [comment]
Warnings aren't ever in violation of the spec; if they are, they would be errors. Generally, warnings are introduced when a developer has a bug and we try to figure out how to catch those issues.

In this particular case, a developer likely had a dependency that was valid because of it being implicit but did not mean for the dependency to exist (used the wrong attachment in one of the subpasses) and spent a while trying to figure out why they were getting the wrong results.

I'll bring this up again and see what others think.

**Comment by lentinem** [comment]
We had another discussion. The consensus was to leave it as it's a warning and it has caught bad behavior. I definitely understand the concern though. Warnings are more to try to help developers without too much of a knowledge of Vulkan but if you consider yourself fairly knowledgeable the recommendation is to disable warnings. We did agree to change the messages to make it more clear that there could be absolutely nothing wrong with what you are doing in the case of a warning. I'm going to keep this open to track the progress of that.

**Comment by chrisforbes** [comment]
This warning since got removed; closing.
