### ISSUE TITLE
Hardcoded RPATH in layers/CMakeLists.txt

### ISSUE THREAD

**Issue by Delwin9999** [KhronosGroup/Vulkan-LoaderAndValidationLayers#548]
Line 34:
set(VK_LAYER_RPATH /usr/lib/x86_64-linux-gnu/vulkan/layer:/usr/lib/i386-linux-gnu/vulkan/layer)

This causes all layers to fail both testing and at runtime if the layers are installed anywhere else.

**Comment by stroyan** [comment]
That RPATH setting is just adding two more places that are searched when resolving shared libraries that the layers depend on.  Many layers depend on libVkLayer_utils.so or libVkLayer_utilsvt.so.  Those can be found in system library paths or anywhere you set LD_LIBRARY_PATH to look.  If you are having trouble loading layers it may be because you don't have that utils library anywhere in your loader search path.

The RPATH setting is out of date, and possibly obsolete.  There is no longer any libVkLayer_utils.so installed in those directories.  It seems that was changed around the time of commit 7bb2c2, on Sep 30, 2015.

**Comment by jon-lunarg** [comment]
Merge request #575 closed so closing this issue
