### ISSUE TITLE
Destroying an Image buffer used in a command buffer?

### ISSUE THREAD

**Issue by Mervill** [KhronosGroup/Vulkan-LoaderAndValidationLayers#641]
This might just be me misunderstanding how Vulkan works, but consider the following:

```C
// Imagine that previously, `imageBuffer` has been filled 
// with an image we want to copy to an Image handle.

// Begin a command buffer
vkBeginCommandBuffer(cmdBuffer, ...)

// Record that we want to copy `imageBuffer` to the target image
vkCmdCopyBufferToImage(cmdBuffer, imageBuffer, targetImage, ...)

// End the command buffer
vkEndCommandBuffer(cmdBuffer);

// We can destroy `imageBuffer` now? How does that make sense?
vkDestroyBuffer(imageBuffer);

// Some time later, submit for execution
vkSubmit(cmdBuffer, ...)

// Image will render correctly
```

As I understand it, command buffers simply 'record' commands to be executed later (when passed to `vkSubmit`). Yet the `imageBuffer` these commands will copy can seemingly be destroyed long before these commands are ever actually executed. Shouldn't I have to wait until this particular command buffer has been executed or freed before I can destroy `imageBuffer`? I've tested this under `VK_LAYER_LUNARG_standard_validation` and it doesn't seem to complain.

**Comment by courtney-g** [comment]
vkDestroyBuffer's valid usage says:

...
All submitted commands that refer to buffer, either directly or via a VkBufferView, must have completed execution
...

Yes, you need to wait until the command buffer is complete before destroying the buffer. The validation layers should throw an error if you were running with them. Were you?

Since the buffer was still in use at vkDestroyBuffer time you violated the Valid Use of vkDestroyBuffer and you enter the realm of "Undefined". Undefined behavior may be nothing happens, things happen to work, segfault the driver, corrupt data, etc. Here you got lucky and though you destroyed the imageBuffer that didn't change the data that was there and so the copy could "work".

**Comment by tobine** [comment]
This is a hole in validation. Currently we'll flag errors if CB dependencies (such as buffers) are destroyed while any CB using such dependencies is in-flight, but only a couple cases are handled of CB dependencies being destroyed prior to CB submission (descriptor sets and framebuffers are the two I know we handle).

There are a few ways to handle this, but my general notion is that anytime such a dependency is destroyed, the CB state for all dependent CBs should be set to CB_INVALID and the error will then be triggered at submission time.

I've got old issue #91 related to this. It's been lower priority until now but I think it now deserves some attention.

I'm out for the rest of the week so I'll leave this issue open for now in case someone wants to spot-fix it. Next week I'll look at this more comprehensively to make sure all CB dependencies are handled uniformly and correctly.

**Comment by tobine** [comment]
#710 fixes this issue. Still doing further work to handle cmd buffer object dependencies beyond images and buffers.

**Comment by tobine** [comment]
Fix was cherry-picked and pushed to master
