### ISSUE TITLE
Feature: Create a layer which validates basic behavior of other layers

### ISSUE THREAD

**Issue by MarkY-LunarG** [KhronosGroup/Vulkan-LoaderAndValidationLayers#671]
During an investigation into a layer being written by someone [Issue #662], Courtney thought of the idea of creating a layer which could validate other layers.  This would allow people to enable this layer below there's (or maybe 2 layers one above and one below) and make sure everything is setup properly.

**Comment by mark-lunarg** [comment]
Karl, is this the right place for this issue?  I'm thinking Jira...

**Comment by karl-lunarg** [comment]
I'd rather approach this by improving the layer development tools.  This would include some sort of easy-to-use sample layer (like the "Starter" layer a few of us have been discussing).  Also useful would be the layer introspect tool.   See @tobine 's [comment ](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/662#issuecomment-227292523) in the other issue.  Perhaps better documentation and tutorials.  In other words, put the quality improvements into the front-end development, instead of "testing the quality in" later, after the fact.

There are not that many layer developers around and building a tool that only a few of them would need seems low ROI.  I also wonder how many problems a layer validation layer could actually discover and diagnose.  Finally, would we need a layer to validate the layer validation layer? :-)

We could leave this issue here to see if we get any more ideas.  But I'll open a LunarG ticket for the layer approach for tracking.

**Comment by mark-lunarg** [comment]
I'd prefer to close this issue and some of the other blue-sky/enhancement issues -- I'd be happy to create a list in the Wiki under the heading of 'Future Enhancements' or something like that. But if this is the best place to track these that's fine.

**Comment by karl-lunarg** [comment]
I've captured everything in JIRA.  I suppose you can close this then.  I realize that we're trying to get the issue count down.

**Comment by mark-lunarg** [comment]
Closing this inactive issue, but will track the content internally.  Thanks!
