### ISSUE TITLE
Verify VkFormatProperties::linearTilingFeatures.

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/Vulkan-LoaderAndValidationLayers#694]
Verify VkFormatProperties::linearTilingFeatures when an application uses a linear texture.

Some implementations of Vulkan don't (officially) support any linear textures and various samples now use linear staging textures without explicitly checking whether or not they are supported:

https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/demos/cube.c
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/demos/tri.c
https://github.com/LunarG/VulkanSamples/blob/master/API-Samples/inittexture/inittexture.cpp

**Comment by Tony-LunarG** [comment]
But all of those samples do look at the linearTilingFeatures for the texture format they are using.  If the FEATURE_SAMPLED_IMAGE bit is set, they go ahead and use the linear format for the texture.  If the bit isn't set, they only use the linear image as a staging buffer (and they should really use a buffer instead of an image), map the memory, load the texture and use a CmdCopyImage to get the pixels out of the linear tiled image and into the optimal tiled texture image which is used for rendering.  Or am I misunderstanding your concern with the samples?

**Comment by mre4ce** [comment]
The concern is that vkCmdCopyImage copies from a linear texture without checking whether or not linear textures are supported at all.

**Comment by mre4ce** [comment]
Is vkCmdCopyImage always supposed to work with linear images? The spec does not explicitly state this, but that would make sense. There are also no feature bits to specify that this would not be supported.

**Comment by karl-lunarg** [comment]
We recently did some work on the screenshot layer (in VulkanTools) and put the following comment in screenshot.cpp:

```
    // There seems to be no way to tell if the swapchain image (image1) is tiled
    // or not.  We therefore assume that the BLIT operation can always read from
    // both linear and optimal tiled (swapchain) images.
    // There is therefore no point in looking at the BLIT_SRC properties.
```

The code in this area handles the job of getting the image bits out of a swapchain image and into a PPM file, so it needs to COPY or BLIT the image from the swapchain to another image that can be mapped by the CPU.  It also does a format conversion so that the code that copies the pixels to the PPM file only needs to work with one format.

Since there's no way to tell if the image is linear or tiled, we have to go ahead and assume that vkCmdCopyImage (and vkCmdBlitImage) can always read from linear images.  So I agree with you that this would make sense, even though it is not explicitly stated.

The code does check to see if CmdBlit can write to linear.  If it can't, then it does the CmdBlit to do the format conversion and then CmdCopy to convert optimal to linear.

**Comment by Tony-LunarG** [comment]
The copy is from a linear image, not texture, and that image is discarded once the copy is done.  The linear image is only used as a texture (sampled) if the format feature bit is set.

**Comment by mre4ce** [comment]
Correct, I meant image instead of texture. My bad. I assumed a copy from a linear image wasn't a required feature.
