### ISSUE TITLE
VulkanRT installer's temporary directory/files should use strong ACLs

### ISSUE THREAD

**Issue by KarenGhavam** [KhronosGroup/Vulkan-LoaderAndValidationLayers#70]
Originally submitted on gitlab by Jeff Juliano. Moved to the public github.

I'm filing this for record. I don't know yet if there is an actual issue.
The VulkanRT installer unpacks a few files that are written to a temporary location. One of the files is a powershell script that is executed from the temporary location with escalated privilege.
The temporary files should employ strong ACLs to ensure there are no timing attacks against the installer during the unpack and install phase.
The point of this issue is to validate that strong ACLs are used. If that's already the case then the issue can be trivially closed. If it's not the case then it needs to be secured. I haven't been able to determine yet if the temporary files are adequately secured.
The final installed loader and uninstaller binaries are themselves secured because they reside in %windir% and %programfiles%, resp. The question is about temporary files during execution of the installer.

**Comment by jjulianoatnv** [comment]
InstallerRT.nsi write the unpacked files to $TEMP.

This page: http://nsis.sourceforge.net/Docs/Chapter4.html
states:
'''
$TEMP

The system temporary directory (usually C:\Windows\Temp but detected at runtime).
'''

Due to issue #136 there is no log file to consult to determine what location was actually used for $TEMP.

What is the real location that gets used on a modern version of the Windows OS?

Does it have an adequate ACL to prevent a non-elevated process from replacing the unpacked files before the elevated installer process executes them?

**Comment by davidlunarg** [comment]
This issue has been addressed with the commit mentioned above. Closing.
