### ISSUE TITLE
Loader: Usage of instance-level extension functions leads to stack corruption & a crash under x64 Windows

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#743]
Let ICD expose an instance-level function vkX(),

An app, which wants to make a good use of the extension, will first create a Vulkan Instance, and then proceed with extracting func pointers for the extended functionality. The _vkGetInstanceProcAddr()_ call is intercepted by the loader and eventually we land in _loader_init_dispatch_dev_ext_entry()_:

![image](https://cloud.githubusercontent.com/assets/17761066/16731454/76e7586a-4778-11e6-81d0-648efad7a950.png)

![image](https://cloud.githubusercontent.com/assets/17761066/16731451/723912fe-4778-11e6-8354-813d68be56c0.png)

As can be seen on the screenshot, there's a bunch of predefined instance extension handlers here. Let's say _vkX()_ is introduced by a different extension. This means we're going to get pulled into _loader_dev_ext_gpa()_:

![image](https://cloud.githubusercontent.com/assets/17761066/16731486/a58d4530-4778-11e6-9908-fb0e24561572.png)

ICD does recognize the function name, so we get to the third if() where a function pointer corresponding to _vkX()_ ends up cached under _inst->disp_hash[hash value]_. This is fine. However, right afterward, the _loader_dev_ext_gpa()_ function returns a function pointer to one of the hard-coded trampoline functions:

![image](https://cloud.githubusercontent.com/assets/17761066/16731566/2c8f4f42-4779-11e6-9abd-73ea2e098116.png)

..which are defined as below..

![image](https://cloud.githubusercontent.com/assets/17761066/16731576/35c05926-4779-11e6-9c44-5b96aec76a7b.png)

This function pointer is returned to the _vkGetInstanceProcAddr()_ caller. This will work if _vkX()_ is defined as _**void (calling convention) vkX(VkDevice device)**_, but will (and does, in fact) crash under Windows, if a different set of arguments is declared.

**Comment by MarkY-LunarG** [comment]
Currently, the loader doesn't support unknown instance extensions.  This is because the instance call-chain ends with the loader terminator.  Since instance calls go out to every ICD, it is important for the loader to pass along the proper information to each ICD.  If the loader doesn't know about an extension, it can't define the proper terminator, and therefore pass the appropriate info.  There are discussions going on about how we can define layer specific instance extensions, but the idea of an ICD supporting such an extension hasn't been broached yet.

**Comment by DominikWitczakAMD** [comment]
Any ETA for this functionality? We may need it in the near future, and it would be great if we did not have to re-implement the same set of validation rules two times in a row ..

**Comment by MarkY-LunarG** [comment]
As I said, this will take a while as we have to redesign some things (if it's even possible) so the soonest I could see it would be two months.  In the meantime, could you give me more information?  Is it possible to implement this as a device extension?  It seems odd that you wouldn't at least want to pass a physical device as your first parameter since an instance is more of a nebulous non-hardware concept.

**Comment by courtney-g** [comment]
Generally speaking, we wouldn't consider something implemented in an ICD as
being an Instance-level extension.

Would there be an issue with calling it a device extension?

On Mon, Jul 11, 2016 at 9:38 AM, Mark Young <notifications@github.com>
wrote:

> As I said, this will take a while as we have to redesign some things (if
> it's even possible) so the soonest I could see it would be two months. In
> the meantime, could you give me more information? Is it possible to
> implement this as a device extension? It seems odd that you wouldn't at
> least want to pass a physical device as your first parameter since an
> instance is more of a nebulous non-hardware concept.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/743#issuecomment-231772835>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAz_URkSo4w6xINadZFX4g6Jv77nGhvWks5qUmNfgaJpZM4JJWTU>
> .
>



-- 
Courtney

**Comment by DominikWitczakAMD** [comment]
Yes, we have important reasons, for which we need specifically an instance-level extension. Unfortunately, I cannot disclose them at this point.

**Comment by MarkY-LunarG** [comment]
This should now be resolved with the vk_icdGetPhysicalDeviceProcAddr functionality introduced simultaenously with the KHR_get_physical_device_properties2 extension.  See the LoaderAndLayerIf.md file for more information on how these should be used.
