### ISSUE TITLE
cube -- bug in WndProc prevents correct resize behaviour

### ISSUE THREAD

**Issue by gary-sweet** [KhronosGroup/Vulkan-LoaderAndValidationLayers#835]
The WM_SIZE case in WndProc in cube.c contains this code:

`demo.height = lParam & 0xffff0000 >> 16;`

Since '>>' has higher precendence than '&' this does not do what is intended. In fact, it actually extracts the width, not the height.

**Comment by Tony-LunarG** [comment]
Fix pushed to master.  The reason we didn't see bad behavior due to this bug is that demo.height and demo.width are only used if the surface capabilities don't specify an extent, which appears to only happen at the initial call to GetPhysicalDeviceSurfaceCapabilitiesKHR.  In subsequent calls to the routine (due to resizes, etc) the current extent is returned and demo.width and demo.height are ignored
