### ISSUE TITLE
Add extension white-list for unique_objects validation layer

### ISSUE THREAD

**Issue by mark-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#887]
The working group has agreed that layers which wrap objects should white-list extensions supported by that layer.  Upon encountering an extension not in the white-list, the layer shall emit an ERROR message and execution shall continue, possibly with undefined results.

The current set of validation layers contains one wrapping layer, unique_objects, to which this feature will be added.  As of header version 1.0.24, the following extensions will be white-listed:

**Instance Extensions:**
- VK_EXT_debug_marker
- VK_EXT_debug_report
- VK_KHR_display
- VK_KHR_surface
- VK_KHR_win32_surface
- VK_KHR_android_surface
- VK_KHR_mir_surface
- VK_KHR_wayland_surface
- VK_KHR_xcb_surface
- VK_KHR_xlib_surface

**Device Extensions:**

- VK_AMD_rasterization_order
- VK_AMD_shader_trinary_minmax
- VK_AMD_shader_explicit_vertex_parameter
- VK_AMD_gcn_shader
- VK_IMG_filter_cubic
- VK_IMG_format_pvrtc
- VK_KHR_sampler_mirror_clamp_to_edge
- VK_KHR_swapchain
- VK_KHR_display_swapchain
- VK_NV_dedicated_allocation
- VK_NV_glsl_shader

**Comment by courtney-g** [comment]
I believe all validation layers will need/want white lists.
For example, if an extension adds / changes the meaning of a command, it would be good to know that a validation layer knows what to do (how to validate) when that extension is present and the white list provides that capability.

**Comment by mark-lunarg** [comment]
@courtney-g , trying to think about how this might work.  So somebody would write a new extension, update a layer or two and add it to the white-list in those particular layers and not update the others (so then you'd get, say, 5 errors instead of 7)?  If the white-lists are all the same it seems like one error message would be OK. Maybe we can talk about this on Wednesday.

**Comment by courtney-g** [comment]
You'd want to add the extension to all layers. That tells you that someone has made sure the layer is compatible with that extension, even if that means the layer doesn't care / change for that extension.

**Comment by DominikWitczakAMD** [comment]
Please note that we released a new VK_AMD_draw_indirect_count extension spec earlier this week. :)

**Comment by karl-lunarg** [comment]
@courtney-g The motivation for the white list was to have a layer try to avoid interacting with an extension in such a way that would cause a crash or other serious problem.  The classic example is a layer passing a handle wrapped by unique_objects to an extension and having the extension crash due to the wrapped handle.

I'm not sure that the motivation for the white list was to indicate the level of completion of validation for an extension.

**Comment by courtney-g** [comment]
@karl-lunarg How do you distinguish between a layer that has been verified to be compatible with an extension vs. one that hasn't? I think the only way this works is if you have a white list for all validation layers.

**Comment by ianelliottus** [comment]
I just noticed this discussion.  This grew out of a Khronos-internal discussion/agreement w.r.t. the wrapping of handles by a layer.  The intention of the agreement was that the unique_objects layer have the white list per what @karl-lunarg said.

Thus, what @courtney-g said is not needed for that agreement.  I'm wondering if what @courtney-g said is meant to extend that idea to indicate validation support?

I'm trying to think this through a bit.  Down the road, when we combine these validation layers into one validation layer (per the plan), the number of checks/errors would decrease.  Seems like we are trying to give the appearance of one validation layer sooner than when the implementation gets there.  As such, my preference (I can be swayed) is that the white list in unique_objects can only be bumped when ALL validation layers support a given extension.  Is that sufficient @courtney-g?

**Comment by ianelliottus** [comment]
Question for @mark-lunarg and @DominikWitczakAMD: do the validation layers support all of these extensions (including the new AMD extension)?

**Comment by karl-lunarg** [comment]
(Just to be clear, I think that we all are thinking through this and designing it here.  The internal discussion result was that we should do white listing, without a lot of detail about the design)

If @courtney-g is extending the concept to indicate support, then that's going to get tricky if white listing is meant to indicate that an extension is tolerated by and happens to work with all validation layers.  We white list an extension to indicate that it is OK to use with layers, but there's no mechanism to indicate that the validation support is complete.  (We don't have a way to do this even for core functions).  But @courtney-g used the word "compatible", so I think he means that the extension works OK (is compatible) with the VLs.

@ianelliottus notion of implementing white list only in unique_objects and letting an extension onto the list only if it is compatible with all the VLs sounds good, but what if you don't load the unique_objects layer?  An extension that is not white listed won't get checked in the non-unique_objects layers and something bad could happen, with no warnings.

I suppose that brings up the question:  "Can anything bad happen if all the VLs are on except unique_objects and an extension is in use?"  We've been advising to turn off only unique_objects when hitting the object wrapping issue, so I'm inclined to say no, but am not completely sure.  If the answer really is no, then that suggests white listing in unique_objects only.

@ianelliottus:  I think that the list of extensions @mark-lunarg posted in the root of this thread are all compatible with layers, since he was proposing to white list them at the start.  I don't know (yet) about the new AMD extension.  @DominikWitczakAMD :  I think that one component of the WG result was that new extension creators need to take the steps to get the extension white listed, whether that means adding code to the VLs, or just requesting to be added to the white list, if no changes are needed.

@mark-lunarg :  What were your motivations for white listing only in unique_objects?

**Comment by courtney-g** [comment]
> If @courtney-g is extending the concept to indicate support, then that's going to get tricky if white listing is meant to indicate that an extension is tolerated by and happens to work with all validation layers. We white list an extension to indicate that it is OK to use with layers, but there's no mechanism to indicate that the validation support is complete. 

Yeah, I figured it was a pretty obvious and useful extension of the white list for wrapped objects.
I would also say that when an extension is white listed, that means any necessary validation for that extension has been added to the validation layers. I think that behavior would be something developers would appreciate.

I can understand reluctance of adopting this meaning in that it implies additional work to support for the extension. Maybe we can indicate "compatible" vs. "complete" via the error reported by the layer?
For example:
- Extension unknown to layer: log error, unsupported extension
- Extension is "compatible" with layer: log warning, "extension validation not complete"
- Extension is "complete": nothing to do.

**Comment by mark-lunarg** [comment]
@ianelliottus and @DominikWitczakAMD , I have added all the extensions that are defined in the 1.0.24 version of the spec, which is what is available on the 1.0 branch in Vulkan-Docs.  This does NOT include the VK_AMD_draw_indirect_count extension.  Dominik, do you know when it'll be defined in the header?

@karl-lunarg , I put this in unique_objects since that's the only layer we know of that is currently affected adversely by any current extension.  I was also trying to avoid the user getting spammed with error messages from each layer saying 'extension XXX is unsupported' -- one should be enough.  For now I plan to put it in unique-objects, but this is another good case for adding the windows shared-memory PR and the message header, then we could check in each layer but only print the scary message one time.

**Comment by ianelliottus** [comment]
I like this 3-way model (unknown, compatible, complete).  I think that's very useful.

I'm flexible on whether each layer reports an error/warning.

> Can anything bad happen if all the VLs are on except unique_objects and an extension is in use?

Yes!  The validation layers implicitly depend on/need unique_objects.

**Comment by karl-lunarg** [comment]
> > Can anything bad happen if all the VLs are on except unique_objects and an extension is in use?

> Yes! The validation layers implicitly depend on/need unique_objects.

I meant in the context where an app can run safely without unique_objects.  IOW, can an extension crash the VLs even when handles are not wrapped?

I suppose that the point is moot since the VLs depend on unique_objects so much.

**Comment by karl-lunarg** [comment]
The 3-way model has an interesting challenge in that someone is going to have to make a call for every extension and for every VL whether or not validation is completely implemented for that extension/VL combination.  How does one know if validation is "complete"?

It also seems weird to put in all this structure for extensions when there is no corresponding "completeness" messaging for core.

**Comment by mark-lunarg** [comment]
See PR #894 .

**Comment by courtney-g** [comment]
To me, "complete" means that someone knowledgeable about the extension and validation layers has verified that the validation layers validate extension use. Yes, "complete" is very fuzzy and probably can't mean that the validation layers will catch all issues with using the extension. But at least someone has looked and made an effort to catch some.

**Comment by DominikWitczakAMD** [comment]
@mark-lunarg : The ETA for AMD_draw_indirect_count is "soon", I guess. It's already published in the registry, so my educated guess would be next header update?

Extending validation layers with support for the ext is on our radar, but I can't tell exactly when this is going to happen at this point.

**Comment by mark-lunarg** [comment]
@DominikWitczakAMD -- we couldn't get 1.0.25 into this SDK, but the changes are now on Master so hopefully this will keep you going.  Let me know right away if you run into any issues.  Thanks!

Whitelist fix pushed to Master
