### ISSUE TITLE
Update Loader and vk_layer.h with common KHR and EXT extension entry points

### ISSUE THREAD

**Issue by MarkY-LunarG** [KhronosGroup/Vulkan-LoaderAndValidationLayers#888]
A number of Vulkan KHR and EXT extensions have been created and aren't directly supported by the layers using the standard dispatch table.  They could be handled by layers in another indirect way, but we should update the dispatch table to include additional entry points.

The extensions I know of that need to be supported are:
 - KHR_display_swapchain
 - EXT_debug_report
 - EXT_debug_marker

The reason this is a harder task than it first appears is that the loader negotiates all layers to the lowest version.  So, if any layer (implicit or explicit) is still using the older version of the header, the other layers will still have to rely on the old mechanism for capturing these entry points.  The loader will also have to do some hand-shaking for these as well.

Additionally, we should add in some extra padding so we can grow these functions without having to bump the revision number in the future.  If a layer doesn't support any functions added later, it should return NULL by default.

**Comment by baldurk** [comment]
What is the impact of changing the structure on the loader/layer interface - do the dispatch tables actually get passed between different components (between loader, a layer, or ICD)?

My understanding was that the dispatch table pointer at the start of each dispatchable object was intended to be an _opaque_ pointer sized object that just so happens to point to the loader's allocated dispatch table, and layers were not supposed to actually cast it to either of the dispatch table types and refer through it. Instead layers were supposed to allocate their own dispatch tables and fill them out with GPA, just using that opaque pointer value as a key. Even if layers did perform such a cast, those function pointers aren't useful since they're the dispatch table for the start of the chain. Only applications could use it and certainly as far as they're concerned the dispatch table pointer is an implementation detail that they cannot use.

I'm mostly wondering because depending on what guarantees are made about the structure and whether layer A can ever legally refer to a dispatch table allocated by layer B or the loader, simply appending to it would remain binary compatible with older layers as they'd just cast it to the older structure as a subset.

If it's not used as part of the ABI at all and is just there for convenience so that layers don't all have to re-implement it (I'm leaning towards this being the case) it can be extended without issue. I'd still strongly argue that you should still append functions no matter what so that any code that just updates vk_layer.h or includes it from the SDK won't percieve any changes except the struct size increasing.

I haven't thought/examined this all the way through though and certainly any change which could possibly be ABI/version breaking should be carefully considered, maybe I'm missing something obvious?

**Comment by MarkY-LunarG** [comment]
The impression I got from Jon before he left that the layers were actively using the dispatch table in a way that would not function properly without all layers being on the same version.  Based on what he said, all layers end up negotiating to use the lowest common denominator for the layer version, and the since the dispatch is used in such a way (let's say non-opaque) that you would not get the new entry points exposed in the easiest to use fashion.   I haven't personally created a layer myself, so I can't say if I'm correct.  I'll work with Mark Lobo as I do this to make sure my understanding is correct.

The concern for Nvidia was particular to making it easier for applications and layers to use known extensions with the loader.

As far as I know, none of this should change an ABI version, just expose all the functionality in the cleanest way.

**Comment by baldurk** [comment]
Hmm, I'm not sure exactly what some of that corresponds to. I'm not aware of any layer version that is negotiated or used - I believe there is a loader-ICD interface version and negotiation, but that's not part of the layer interface.

From my perspective as a layer author the dispatch table structs are all allocated and used within my layer - I never access the loader's, nor any other layer's further down the chain. Even accessing the loader's dispatch table is of no practical use, since calling any of those functions would result in re-entrancy as it calls down the chain to my layer again. Any vulkan functions the layer has to call happen from the dispatch table I initialise myself, which comes from populating my own table using the GPA function `pLayerInfo->pfnNextGetInstanceProcAddr` in the `VK_LAYER_LINK_INFO` struct attached to the `pNext` chain in `vkCreateInstance` or `vkCreateDevice` depending on which dispatch chain you mean, which lets me populate a table from the next layer (or the ICD if I'm the last layer in the chain).

Having said that maybe there are some use of dispatch tables I'm not aware of, but I don't know what you're meaning since there's definitely not any required use of them (it'd be perfectly possible to write a layer that didn't use dispatch tables at all, they're just a very convenient concept to keep everything together).

As for extensions - I've already extended my dispatch table to include the EXT_debug_marker extension functions, since I know my table is only ever used within my layer. Propagating it upstream to the vk_layer.h table would certainly make it easier for layer authors rather than having to reimplement it (more or less depending on if they're using the helper functions in the loader code to populate the tables), but I'm not sure it would change much for application developers - that would be more affected by having trampoline functions provided for extensions like is already the case for the WSI extensions.

**Comment by MarkY-LunarG** [comment]
You could be right, I'm definitely still working out some of these things about Loader/Layer interaction.  I just remember what he said based on my previous attempt to add entry points from the KHR_display_swapchain extension to the dispatch table in vk_layer.h.

**Comment by courtney-g** [comment]
The dispatch table in vk_layer.h is the dispatch table used by the loader's trampoline functions. Layers don't have to use it, but it's convenient and allows the layers to use common init code.

**Comment by ianelliottus** [comment]
> The dispatch table in vk_layer.h is the dispatch table used by the loader's trampoline functions. Layers don't have to use it, but it's convenient and allows the layers to use common init code.

Clarifying question for @courtney-g: For any layer that does use this dispatch table, solely within its layer code, can there be a problem if LunarG adds new functions?

In other words, as long as each layer only uses the version of the struct that it compiled into itself, I'm guessing there isn't any trouble with different layers compiling in different versions of the struct.  True?

**Comment by MarkY-LunarG** [comment]
I don't believe the layer will have an issue.  I think this might be a loader/layer interaction issue.  Although, I still am not sure to what extent.  I'm investigating now.

**Comment by courtney-g** [comment]
> Clarifying question for @courtney-g: For any layer that does use this dispatch table, solely within its layer code, can there be a problem if LunarG adds new functions?

Not that I know of. Especially if new functions are added at the end of the list.

**Comment by MarkY-LunarG** [comment]
That's my belief as well after looking at the code.

**Comment by MarkY-LunarG** [comment]
Ok.  After talking offline with Courtney, we believe I was mistaken over the scope of this.  These changes should be in the next SDK (not this weeks, but the next one post-1.0.24).

**Comment by MarkY-LunarG** [comment]
After MarkM's changes for 1.0.25, I've added the remaining extensions.  No problems seen when trying to use them with mismatching layers (including renderdoc).  Commit: c827a5880dc3fabfc7d1a58bb62798649cab1181.
