### ISSUE TITLE
Crash on ValidateImageMemoryIsValid

### ISSUE THREAD

**Issue by RCalocaO** [KhronosGroup/Vulkan-LoaderAndValidationLayers#915]
_getImageNode(dev_data, fb_info.image)_ is returning null, and then _ValidateImageMemoryIsValid()_ will try to dereference the nullptr on _if (image_node->mem == MEMTRACKER_SWAP_CHAIN_IMAGE_KEY)_. The image got deleted before this submit. Callstack:
>	VkLayer_core_validation.dll!core_validation::ValidateImageMemoryIsValid(dev_data=0x00000000214bc490, image_node=0x0000000000000000, functionName=0x000007fec4f619c8) Line 459	C++
 	VkLayer_core_validation.dll!core_validation::CmdBeginRenderPass::__l24::<lambda>() Line 9994	C++
 	VkLayer_core_validation.dll!std::_Callable_obj<bool <lambda>(void),0>::_ApplyX<bool>() Line 284	C++
 	VkLayer_core_validation.dll!std::_Func_impl<std::_Callable_obj<bool <lambda>(void),0>,std::allocator<std::_Func_class<bool> >,bool>::_Do_call() Line 229	C++
 	VkLayer_core_validation.dll!std::_Func_class<bool>::operator()() Line 316	C++
 	VkLayer_core_validation.dll!core_validation::QueueSubmit(queue=0x000000001bf9ae60, submitCount=1, pSubmits=0x000000003122d250, fence=0x0000000000002d11) Line 4917	C++
 	VkLayer_object_tracker.dll!object_tracker::QueueSubmit(queue=0x000000001bf9ae60, submitCount=1, pSubmits=0x000000003122d250, fence=0x0000000000002d11) Line 635	C++
 	VkLayer_parameter_validation.dll!parameter_validation::QueueSubmit(queue=0x000000001bf9ae60, submitCount=1, pSubmits=0x000000003122d250, fence=0x0000000000002d11) Line 1802	C++
 	VkLayer_threading.dll!threading::QueueSubmit(queue=0x000000001bf9ae60, submitCount=1, pSubmits=0x000000003122d250, fence=0x0000000000002d11) Line 129	C++
 	VkLayer_api_dump.dll!vkQueueSubmit(queue=0x000000001bf9ae60, submitCount=1, pSubmits=0x000000003122d250, fence=0x0000000000002d11) Line 582	C++
 	UE4Editor-VulkanRHI-Win64-Debug.dll!FVulkanQueue::Submit(CmdBuffer=0x0000000017e3bcd0, WaitSemaphore=0x00000000410f1600, WaitStageFlags=8192, SignalSemaphore=0x0000000000000000) Line 70	C++

**Comment by tobine** [comment]
Hi @RCalocaO, I believe I see the issue. When you say "the image got deleted" I assume that the framebuffer is still valid. This reveals a hole in our invalid command buffer handling. We create a binding between the framebuffer and cmd buffer, but not the underlying images of the framebuffer. Need to include bindings for the underlying images.
If things were working correctly you'd see an error due to invalid cmd buffer before hitting the null ptr. More details below, primarily for my benefit as I make sure to correctly fix this.

What should happen is that at CmdBeginRenderPass time a binding is created between the cmd buffer and the framebuffer used in the renderpass as well as images within the framebuffer attachments. Then, if the framebuffer's images are destroyed the cmd buffer is transitioned to INVALID state so that on the next submit you receive an error that said "cmd buffer invalid b/c bound framebuffer/image (0x##) was destroyed."

Writing the test will probably take longer than the fix but hopefully have something tomorrow.

**Comment by RCalocaO** [comment]
That's exactly the issue. Thanks!
