### ISSUE TITLE
Layers/Loader: Separate WSI extensions should look for their own enable

### ISSUE THREAD

**Issue by MarkY-LunarG** [KhronosGroup/Vulkan-LoaderAndValidationLayers#929]
Right now, the loader and layers appear to be enabling all WSI entry points if only one of the WSI extensions is present.  Instead, we should only enable the entry points of a WSI extension if that extension is explicitly enabled.

**Comment by MarkY-LunarG** [comment]
Another thing I should point out is that this has historically been done by the layers.  However, the loader should really be doing this.  In other words, all WSI entry points (whether instance or device) should go through a loader entry point.  Part of that entry point's behavior should be making sure that the corresponding extension for that entry point has been enabled.  This breaks one of the vk_layer_tests which expects to get a validation error.  However, the loader should attempt to throw the corresponding error.  I'm not entirely certain how to do that from a device, but in an instance function, we can call the log function (which should trigger a debug_report message).

**Comment by courtney-g** [comment]
To catch use of un-enabled WSI extensions most of the layers will return NULL to G*PA requests if the extension is disabled (that allows the working code to forgo the enable check since app will only get address if it's enabled). Paramchecker, however, will always return a function pointer and in the call it will check and assert an error if the extension was not enabled.

**Comment by MarkY-LunarG** [comment]
My concern is if layers aren't enabled, an ICD supports the given entry point, and the loader passes it along.  An ICD might choke if an extension entry point is called, but not enabled.

**Comment by courtney-g** [comment]
We are not supposed to protect the ICD. Such protection is done in validation layers and when the layers aren't there, the checks are gone.
If the API is not used in a valid fashion the results are "undefined" that can mean that the app dies. That's allowed.

**Comment by MarkY-LunarG** [comment]
Ok.  This still may apply for the procaddr queries in the loader, so I'll leave loader in the title for now.

**Comment by ianelliottus** [comment]
I'm late to this party.  I thought that the loader did a good job of using separate "enabled" variables for each extension.  The swapchain layer did the checking (unless somebody moved that code out) for whether the extension is enabled.

@courtney-g, I thought that you added code to the Android loader to do enablement checking, since the WSI entrypoints are statically exported (i.e. can be called by an app without needing to call GPA).  True?

Seems like we want that in the desktop loader as well.  True?

**Comment by courtney-g** [comment]
My understanding is that this issue was introduced with the newly added VK_KHR_display and VK_KHR_display_swapchain extension.

**Comment by MarkY-LunarG** [comment]
I thought I saw some validation in some of the layers always relying on only one of the extensions being present and then saying that all the WSI extensions were enabled by default.  I'll have to look it up again.

**Comment by MarkY-LunarG** [comment]
I believe these are resolved now.  We'll re-open if I encounter a specific one.
