### ISSUE TITLE
smoke swapchain validation error

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#93]
When running "smoke --validate" it reports the following validation error repeatedly:
Swapchain: vkAcquireNextImageKHR() called when the application already owns all presentable images in this swapchain except for the image currently being displayed.  This call to vkAcquireNextImageKHR() cannot succeed unless another thread calls the vkQueuePresentKHR() function in order to release ownership of one of the presentable images of this swapchain.

Here's olv's comment on this error:

There is a bit of ambiguity but I think it is a layer issue.  nVidia
reports minImageCount to be 1.  That means when the display server
owns 1 image, apps can acquire it.  But layers think the only
image owned by the display server is being presented.  It cannot be acquired.

Ian, assigning this to you initially to determine the correct fix and re-assign as appropriate.

**Comment by ianelliottus** [comment]
I had assumed (and told Tony) that this was an NVIDIA driver issue.  However, Jeff Juliano of NVIDIA has raised a WSI spec issue (internal to Khronos) about minImageCount for what he describes as "BlitModel".  The basic idea of this model is that, when deemed feasible, the NVIDIA driver only uses 1 swapchain image, which it blits to an underlying Windows buffer at presentation time.  vkAcquireNextImageKHR() returns the just-presented image, since that blit will eventually finish ("in finite time"), at which time, the semaphore/fence will be signaled.

The WSI portion of the Vulkan spec (both description and example code) is definitely written from the perspective of what Jeff describes as a "FlipModel", where 1 image of a swapchain is being displayed, and as such, isn't available for being acquired/owned by the application.  That is why the validation layer is complaining--because the 1 image of the swapchain is assumed to be displayed, and therefore, the "presentation engine" cannot possibly provide another image for the vkAcquireNextImageKHR() call.

I will update this issue when we resolve that internal-to-Khronos issue.

**Comment by ianelliottus** [comment]
Closing ... The WSI spec issue was resolved within the Khronos (and the new text should release within a day or two).  The swapchain validation layer was updated with a new test and error message (which change was pushed to "master").  This should work on Windows now, and certainly works on Linux.
